
import test from "node:test";
import assert from "node:assert/strict";
import { calculateBusinessCase, numberValue } from "../src/calculations.js";
import { defaultProject, migrateProject } from "../src/model.js";
import { formatMoney, formatNumber } from "../src/i18n.js";

test("decimal parser accepts European and English formats",()=>{assert.equal(numberValue("0,25"),.25);assert.equal(numberValue("0.25"),.25);assert.equal(numberValue("1.250,50"),1250.5);assert.equal(numberValue("1250.50"),1250.5)});
test("Italian formatting always shows four-digit thousands separators",()=>{assert.match(formatNumber(8184,"it"),/8\.184/);assert.match(formatMoney(4641,"it"),/4\.641/)});
test("LED only gates all smart savings and costs",()=>{const p=defaultProject();p.solution.smartEnabled=false;p.solution.cmsEnabled=false;p.solution.powerAidEnabled=false;const r=calculateBusinessCase(p);assert.equal(r.lcuQuantity,0);assert.equal(r.smartHardwareCapex,0);assert.equal(r.cmsOpex,0);assert.equal(r.cloSavingKwh,0);assert.equal(r.powerAidSavingKwh,0);assert.equal(r.powerAidFee,0)});
test("Smart calculates automatic LCU and CLO without PowerAiD",()=>{const p=defaultProject();p.solution.powerAidEnabled=false;const r=calculateBusinessCase(p);assert.equal(r.lcuQuantity,100);assert.ok(r.cloSavingKwh>0);assert.equal(r.powerAidSavingKwh,0);assert.equal(r.powerAidFee,0)});
test("PowerAiD applies after CLO and fee only to its saving",()=>{const p=defaultProject();p.solution.powerAidEnabled=true;const r=calculateBusinessCase(p);const after=r.ledKwh-r.cloSavingKwh;assert.ok(Math.abs(r.powerAidSavingKwh-after*.4)<1e-9);assert.ok(Math.abs(r.powerAidFee-r.powerAidSavingKwh*p.assumptions.energyPrice*.2)<1e-9)});
test("CLO and PowerAiD respect per-group Smart and PowerAiD assignments",()=>{const p=defaultProject();p.solution.powerAidEnabled=true;p.groups=[{...p.groups[0],id:"smart",quantity:10,smartAssigned:true,powerAidAssigned:true},{...p.groups[0],id:"plain",quantity:10,smartAssigned:false,powerAidAssigned:false}];const r=calculateBusinessCase(p);const smartLed=10*40*p.assumptions.operatingHours/1000;assert.equal(r.lcuQuantity,10);assert.ok(Math.abs(r.cloSavingKwh-smartLed*.1)<1e-9);assert.ok(Math.abs(r.powerAidSavingKwh-smartLed*.9*.4)<1e-9)});
test("cash and financed payments separate service OPEX from financing",()=>{const cash=defaultProject();const cashResult=calculateBusinessCase(cash);assert.equal(cashResult.financingMonthlyPayment,0);assert.equal(cashResult.monthlyPayment,cashResult.totalAnnualOpex/12);const financed=defaultProject();financed.assumptions.dealType="noleggio_operativo";assert.ok(calculateBusinessCase(financed).financingMonthlyPayment>0)});
test("Finance solution, LaaS and PPP use financing while Cash Deal does not",()=>{for(const model of ["finance","noleggio_operativo"]){const p=defaultProject();p.assumptions.dealType=model;assert.ok(calculateBusinessCase(p).monthlyPayment>0,model)}const cash=defaultProject();cash.assumptions.dealType="cash";const cashResult=calculateBusinessCase(cash);assert.equal(cashResult.financingMonthlyPayment,0);assert.equal(cashResult.monthlyPayment,cashResult.totalAnnualOpex/12)});
test("financing includes monthly compound interest",()=>{const p=defaultProject();p.assumptions.dealType="noleggio_operativo";p.assumptions.interestRate=8;p.assumptions.contractYears=10;const r=calculateBusinessCase(p);const rate=.08/12,months=120,expected=r.totalCapex*rate/(1-Math.pow(1+rate,-months));assert.ok(Math.abs(r.financingMonthlyPayment-expected)<1e-9);assert.ok(r.annualPayment>r.totalCapex/10)});
test("annual customer net benefit deducts the complete customer payment",()=>{const p=defaultProject();p.assumptions.dealType="finance";const r=calculateBusinessCase(p);assert.ok(r.totalAnnualOpex>0);assert.ok(r.financingAnnualPayment>0);assert.equal(r.customerAnnualPayment,r.financingAnnualPayment+r.totalAnnualOpex);assert.equal(r.customerAnnualNetBenefit,r.grossBenefit-r.customerAnnualPayment)});
test("cash-flow rows deduct OPEX exactly once for every deal type",()=>{for(const dealType of ["cash","finance","noleggio_operativo"]){const p=defaultProject();p.assumptions.dealType=dealType;if(dealType==="noleggio_operativo")p.assumptions.allInclusiveAnnualPayment=12000;const row=calculateBusinessCase(p).cashFlowRows[0];const expected=dealType==="noleggio_operativo"?row.grossBenefit-row.payment:row.grossBenefit-row.opex-row.payment;assert.equal(row.netCashFlow,expected,dealType)}});
test("project overrides apply without changing catalogue master values",()=>{const p=defaultProject();p.pricing.overrides["lcu-1"]={salesPrice:62,annualSalesPrice:2};const r=calculateBusinessCase(p);assert.equal(r.smartHardwareCapex,100*62);assert.equal(r.cmsOpex,100*2);assert.equal(p.catalogue.smart[0].salesPrice,45);assert.equal(p.catalogue.smart[0].annualSalesPrice,5)});
test("internal margin deducts all configured direct project costs",()=>{const p=defaultProject();p.assumptions.dealType="noleggio_operativo";p.assumptions.commissionPercent=5;p.assumptions.warrantyReservePercent=2;p.assumptions.fundingCostPercent=3;p.assumptions.otherDirectCosts=1000;const r=calculateBusinessCase(p);assert.equal(r.totalDirectCosts,r.capexDirectCost+r.contractOpexCost+r.commissionCost+r.warrantyReserve+r.financingCost+1000);assert.equal(r.netProjectProfit,r.totalContractRevenue-r.totalDirectCosts)});
test("GO requires customer viability and the configured minimum net margin",()=>{const p=defaultProject();p.assumptions.minimumMarginPercent=30;assert.equal(calculateBusinessCase(p).customerDecisionStatus,"GO");p.assumptions.commissionPercent=100;const r=calculateBusinessCase(p);assert.equal(r.customerDecisionStatus,"GO");assert.equal(r.decisionStatus,"NO_GO")});
test("old project data safely receives new fields",()=>{const p=migrateProject({project:{name:"Old"},groups:[]});assert.equal(p.project.name,"Old");assert.equal(p.language,"it");assert.ok(p.assumptions.sapFactor)});

test("cash deal TCV is cash CAPEX plus separate contract OPEX",()=>{const p=defaultProject();p.assumptions.dealType="cash";p.assumptions.opexEscalation=0;const r=calculateBusinessCase(p);assert.equal(r.totalContractRevenue,r.totalCapex+r.totalAnnualOpex*p.assumptions.contractYears);assert.equal(r.financingAnnualPayment,0)});
test("Noleggio Operativo uses only the all-inclusive payment and does not double count OPEX",()=>{const p=defaultProject();p.assumptions.dealType="noleggio_operativo";p.assumptions.contractYears=9;p.assumptions.allInclusiveAnnualPayment=113208;const r=calculateBusinessCase(p);assert.equal(r.totalContractRevenue,113208*9);assert.equal(r.contractOpexRevenue,0);assert.equal(r.customerAnnualPayment,113208)});
test("finance solution combines financed hardware and separate OPEX",()=>{const p=defaultProject();p.assumptions.dealType="finance";p.assumptions.financingYears=9;p.assumptions.contractYears=9;p.assumptions.opexEscalation=0;const r=calculateBusinessCase(p);assert.equal(r.totalContractRevenue,r.capexContractRevenue+r.totalAnnualOpex*9);assert.equal(r.customerAnnualPayment,r.financingAnnualPayment+r.totalAnnualOpex)});
test("legacy LaaS projects migrate to Noleggio Operativo",()=>{const p=migrateProject({assumptions:{financingModel:"laas"},groups:[]});assert.equal(p.assumptions.dealType,"noleggio_operativo")});

test("official imported CAPEX and OPEX override catalogue calculations",()=>{const p=defaultProject();p.assumptions.officialOfferCapex=388248;p.assumptions.officialAnnualOpex=32022;p.assumptions.dealType="noleggio_operativo";p.assumptions.contractYears=9;p.assumptions.financingYears=9;p.assumptions.allInclusiveAnnualPayment=92675.88;const r=calculateBusinessCase(p);assert.equal(r.totalCapex,388248);assert.equal(r.totalAnnualOpex,32022);assert.ok(Math.abs(r.totalContractRevenue-834083)<1)});
