import React, { useEffect, useMemo, useState } from "react";
import { calculateBusinessCase, numberValue } from "./calculations.js";
import { defaultProject, loadProjects, migrateProject, uid } from "./model.js";
import { formatMoney, formatNumber, formatPercent, useT } from "./i18n.js";
import { generateCustomerPdf } from "./report.js";
import "./styles.css";

const workflow = [["customer","customer"],["existing","existing"],["solution","solution"],["pricing","pricing"],["assumptions","assumptions"],["business","business"],["report","report"]];
const numeric = new Set(["quantity","existingWattage","wattage","lumen","costPrice","salesPrice","implementationCost","implementationSalesPrice","annualCost","annualSalesPrice","gatewayQuantity","antennaQuantity","meterQuantity","operatingHours","energyPrice","sapFactor","mhFactor","mercuryFactor","co2KgPerKwh","cloPercent","powerAidPercent","powerAidSharePercent","existingMaintenance","newMaintenance","contractYears","interestRate","upfrontPayment","energyEscalation","opexEscalation","discountRate","analysisPeriod","freightCostPerLamp","freightSalesPerLamp"]);

export default function App(){
  const initial=useMemo(loadProjects,[]); const [projects,setProjects]=useState(initial); const [activeId,setActiveId]=useState(initial[0].id); const [view,setView]=useState("customer");
  const project=projects.find(p=>p.id===activeId)||projects[0]; const t=useT(project.language); const result=useMemo(()=>calculateBusinessCase(project),[project]);
  useEffect(()=>localStorage.setItem("vimalux-intelligence-projects",JSON.stringify(projects)),[projects]);
  const update=(path,value)=>setProjects(all=>all.map(p=>p.id!==project.id?p:setPath(p,path,numeric.has(path.at(-1))?numberValue(value):value)));
  const money=v=>formatMoney(v,project.language,project.project.currency); const num=(v,d=0)=>formatNumber(v,project.language,d);
  const create=()=>{const p=defaultProject();setProjects(x=>[...x,p]);setActiveId(p.id);setView("customer")};
  const reset=()=>{if(confirm(project.language==="it"?"Eliminare tutti i dati locali e ripristinare i valori iniziali?":"Delete all local data and restore defaults?")){const p=defaultProject();localStorage.removeItem("vimalux-intelligence-projects");setProjects([p]);setActiveId(p.id);setView("customer")}};
  return <div className="app"><aside><div className="brand"><span>V</span><div><strong>VIMALUX</strong><small>Intelligence v1.0</small></div></div><nav>{workflow.map(([id,key],i)=><button className={view===id?"active":""} onClick={()=>setView(id)} key={id}><b>{i+1}</b>{t(key)}</button>)}</nav><hr/><button className={view==="projects"?"active":""} onClick={()=>setView("projects")}>{t("projects")}</button><button className={view==="catalogue"?"active":""} onClick={()=>setView("catalogue")}>{t("catalogue")}</button><button className={view==="admin"?"active":""} onClick={()=>setView("admin")}>{t("priceAdmin")}</button></aside>
  <main><header><div><small>{project.project.businessCaseId}</small><h1>{t(workflow.find(x=>x[0]===view)?.[1]||view)}</h1></div><div className="header-actions"><span className="saved">● {t("save")}</span><select value={project.language} onChange={e=>update(["language"],e.target.value)} aria-label="Language"><option value="it">Italiano</option><option value="en">English</option></select></div></header>
  {view==="customer"&&<Customer p={project} update={update}/>} {view==="existing"&&<Existing p={project} update={update} t={t}/>} {view==="solution"&&<Solution p={project} r={result} update={update} t={t} money={money}/>} {view==="pricing"&&<Pricing p={project} r={result} update={update} t={t} money={money}/>} {view==="assumptions"&&<Assumptions p={project} update={update}/>} {view==="business"&&<Business p={project} r={result} t={t} money={money} num={num}/>} {view==="report"&&<Report p={project} r={result} t={t} money={money} num={num}/>} {view==="projects"&&<Projects list={projects} activeId={activeId} select={id=>{setActiveId(id);setView("customer")}} create={create} t={t}/>} {view==="catalogue"&&<Catalogue p={project} update={update}/>} {view==="admin"&&<Admin reset={reset} t={t}/>} </main></div>;
}

function setPath(object,path,value){const copy=structuredClone(object);let cursor=copy;path.slice(0,-1).forEach(k=>cursor=cursor[k]);cursor[path.at(-1)]=value;return migrateProject(copy)}
const Field=({label,value,onChange,type="text",children})=><label><span>{label}</span>{children?<select value={value} onChange={e=>onChange(e.target.value)}>{children}</select>:<input type={type} value={value??""} onChange={e=>onChange(e.target.value)}/>}</label>;
const Toggle=({label,value,onChange})=><label className="toggle"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;
const Card=({title,children})=><section className="card"><h2>{title}</h2>{children}</section>;

function Customer({p,update}){const c=[["name",p.language==="it"?"Comune / cliente":"Municipality / customer"],["province",p.language==="it"?"Provincia":"Province"],["region",p.language==="it"?"Regione":"Region"],["country",p.language==="it"?"Paese":"Country"],["contact",p.language==="it"?"Referente":"Contact person"],["title",p.language==="it"?"Ruolo":"Position / title"],["email","Email"],["telephone",p.language==="it"?"Telefono":"Telephone"]];const q=[["name",p.language==="it"?"Nome progetto":"Project name"],["businessCaseId","Business Case ID"],["consultant",p.language==="it"?"Consulente commerciale":"Sales consultant"],["date",p.language==="it"?"Data":"Date"],["currency",p.language==="it"?"Valuta":"Currency"]];return <div className="two-col"><Card title={p.language==="it"?"Cliente":"Customer"}><div className="form-grid">{c.map(([k,l])=><Field key={k} label={l} value={p.customer[k]} onChange={v=>update(["customer",k],v)}/>)}</div></Card><Card title={p.language==="it"?"Progetto":"Project"}><div className="form-grid">{q.map(([k,l])=><Field key={k} label={l} type={k==="date"?"date":"text"} value={p.project[k]} onChange={v=>update(["project",k],v)}/>)}</div></Card></div>}
function Existing({p,update,t}){const add=()=>update(["groups"],[...p.groups,{id:uid(),name:`${p.language==="it"?"Gruppo":"Group"} ${p.groups.length+1}`,quantity:0,technology:"SAP",existingWattage:0,proposedProductId:p.catalogue.led[0]?.id||"",smartAssigned:true,powerAidAssigned:true}]);const remove=id=>update(["groups"],p.groups.filter(g=>g.id!==id));return <Card title={t("existing")}><div className="table-scroll"><table><thead><tr>{[p.language==="it"?"Gruppo":"Group",p.language==="it"?"Quantità":"Quantity",p.language==="it"?"Tecnologia":"Technology",p.language==="it"?"Potenza esistente":"Existing wattage",p.language==="it"?"Prodotto LED":"Proposed LED","Smart Lighting","PowerAiD",""].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{p.groups.map((g,i)=><tr key={g.id}><td><input value={g.name} onChange={e=>update(["groups",i,"name"],e.target.value)}/></td><td><input value={g.quantity} onChange={e=>update(["groups",i,"quantity"],e.target.value)}/></td><td><select value={g.technology} onChange={e=>update(["groups",i,"technology"],e.target.value)}>{[["SAP","SAP / HPS"],["MH","MH"],["MERCURY","Mercury / HQL"],["LED","Existing LED"],["OTHER","Other"]].map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></td><td><input value={g.existingWattage} onChange={e=>update(["groups",i,"existingWattage"],e.target.value)}/></td><td><select value={g.proposedProductId} onChange={e=>update(["groups",i,"proposedProductId"],e.target.value)}>{p.catalogue.led.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.brand} {x.name} · {x.wattage} W</option>)}</select></td><td><input type="checkbox" checked={g.smartAssigned} onChange={e=>update(["groups",i,"smartAssigned"],e.target.checked)}/></td><td><input type="checkbox" checked={g.powerAidAssigned} onChange={e=>update(["groups",i,"powerAidAssigned"],e.target.checked)}/></td><td><button className="danger" onClick={()=>remove(g.id)}>{t("remove")}</button></td></tr>)}</tbody></table></div><button className="primary" onClick={add}>+ {t("add")}</button><p className="hint">SAP / HPS: {p.assumptions.sapFactor}× · MH: {p.assumptions.mhFactor}× · Mercury / HQL: {p.assumptions.mercuryFactor}×</p></Card>}
function ProductSelect({label,type,p,value,onChange}){return <Field label={label} value={value} onChange={onChange}>{p.catalogue.smart.filter(x=>x.type===type&&x.active).map(x=><option key={x.id} value={x.id}>{x.brand} {x.name}</option>)}</Field>}
function Solution({p,r,update,t,money}){return <div className="two-col"><Card title={t("solution")}><div className="toggles"><Toggle label="Smart Lighting" value={p.solution.smartEnabled} onChange={v=>update(["solution","smartEnabled"],v)}/><Toggle label="CMS" value={p.solution.cmsEnabled} onChange={v=>update(["solution","cmsEnabled"],v)}/><Toggle label="PowerAiD" value={p.solution.powerAidEnabled} onChange={v=>update(["solution","powerAidEnabled"],v)}/></div><div className="form-grid"><ProductSelect label="LCU" type="LCU" p={p} value={p.solution.lcuProductId} onChange={v=>update(["solution","lcuProductId"],v)}/><ProductSelect label="Gateway" type="Gateway" p={p} value={p.solution.gatewayProductId} onChange={v=>update(["solution","gatewayProductId"],v)}/><Field label={p.language==="it"?"Quantità gateway":"Gateway quantity"} value={p.solution.gatewayQuantity} onChange={v=>update(["solution","gatewayQuantity"],v)}/><ProductSelect label="Antenna" type="Antenna" p={p} value={p.solution.antennaProductId} onChange={v=>update(["solution","antennaProductId"],v)}/><Field label={p.language==="it"?"Quantità antenne":"Antenna quantity"} value={p.solution.antennaQuantity} onChange={v=>update(["solution","antennaQuantity"],v)}/><ProductSelect label={p.language==="it"?"Contatore":"Energy meter"} type="Energy Meter" p={p} value={p.solution.meterProductId} onChange={v=>update(["solution","meterProductId"],v)}/><Field label={p.language==="it"?"Quantità contatori":"Meter quantity"} value={p.solution.meterQuantity} onChange={v=>update(["solution","meterQuantity"],v)}/></div></Card><Card title={p.language==="it"?"Riepilogo hardware Smart":"Smart hardware summary"}><div className="lcu-callout"><small>{p.language==="it"?"Quantità LCU calcolata":"Calculated LCU quantity"}</small><strong>{r.lcuQuantity} {t("units")}</strong><span>{p.language==="it"?"Calcolata dalle assegnazioni Smart Lighting":"Calculated from Smart Lighting assignments"}</span></div><Breakdown rows={[["LCU",r.lcuQuantity,r.smartHardwareCapex],[p.language==="it"?"Implementazione":"Implementation",r.lcuQuantity,r.implementationCapex],["CMS",r.lcuQuantity,r.cmsOpex],["Gateway",r.hardware.gatewayQty,r.gatewayCapex],["Gateway OPEX",r.hardware.gatewayQty,r.gatewayOpex],["Antenna",r.hardware.antennaQty,r.antennaCapex],[p.language==="it"?"Contatore":"Energy meter",r.hardware.meterQty,r.meterCapex]]} money={money}/></Card></div>}
const Breakdown=({rows,money})=><div className="breakdown">{rows.map(([l,q,total])=><div key={l}><span>{l}</span><span>{q} × {q?money(total/q):money(0)}</span><strong>{money(total)}</strong></div>)}</div>;
function Pricing({p,r,update,t,money}){const rows=[...r.groupRows.map((g,i)=>({id:g.product.id,label:`LED · ${g.product.name}`,q:g.quantity,cost:g.product.costPrice,cat:g.product.salesPrice,total:g.salesTotal,index:i})),{id:"lcu",label:"LCU",q:r.lcuQuantity,cost:r.hardware.lcu.costPrice,cat:r.hardware.lcu.salesPrice,total:r.smartHardwareCapex},{id:"implementation",label:p.language==="it"?"Implementazione LCU":"LCU implementation",q:r.lcuQuantity,cost:r.hardware.lcu.implementationCost,cat:r.hardware.lcu.implementationSalesPrice,total:r.implementationCapex},{id:"gateway",label:"Gateway",q:r.hardware.gatewayQty,cost:r.hardware.gateway.costPrice,cat:r.hardware.gateway.salesPrice,total:r.gatewayCapex},{id:"antenna",label:"Antenna",q:r.hardware.antennaQty,cost:r.hardware.antenna.costPrice,cat:r.hardware.antenna.salesPrice,total:r.antennaCapex},{id:"meter",label:p.language==="it"?"Contatore":"Energy meter",q:r.hardware.meterQty,cost:r.hardware.meter.costPrice,cat:r.hardware.meter.salesPrice,total:r.meterCapex},{id:"freight",label:p.language==="it"?"Trasporto":"Freight",q:r.totalQuantity,cost:p.assumptions.freightCostPerLamp,cat:p.assumptions.freightSalesPerLamp,total:r.freight}];return <Card title={t("pricing")}><div className="table-scroll"><table><thead><tr>{[p.language==="it"?"Componente":"Component",p.language==="it"?"Quantità":"Quantity",p.language==="it"?"Prezzo catalogo":"Catalogue price",p.language==="it"?"Costo":"Cost",p.language==="it"?"Prezzo progetto":"Project override",p.language==="it"?"Vendite totali":"Total sales",p.language==="it"?"Margine":"Margin"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((x,i)=>{const sale=x.q?x.total/x.q:0,margin=x.total-x.q*(x.cost||0);return <tr key={x.id+i}><td>{x.label}</td><td>{x.q}</td><td>{money(x.cat)}</td><td>{money(x.cost)}</td><td>{x.index!=null?<input value={p.groups[x.index].projectLedPrice??""} placeholder={String(x.cat)} onChange={e=>update(["groups",x.index,"projectLedPrice"],e.target.value===""?null:numberValue(e.target.value))}/>:money(sale)}</td><td>{money(x.total)}</td><td className={margin<0?"negative":"positive"}>{money(margin)}</td></tr>})}</tbody></table></div><div className="summary-line"><span>{t("capex")}</span><strong>{money(r.totalCapex)}</strong></div><p className="hint">{p.language==="it"?"I prezzi specifici del progetto non modificano i valori del catalogo.":"Project-specific prices do not modify catalogue defaults."}</p></Card>}
const assumptionGroups={Technical:[["operatingHours","Annual operating hours"],["energyPrice","Energy price (EUR/kWh)"],["sapFactor","SAP factor"],["mhFactor","MH factor"],["mercuryFactor","Mercury factor"],["co2KgPerKwh","CO₂ kg/kWh"]],Savings:[["cloPercent","CLO percentage"],["powerAidPercent","PowerAiD percentage"],["powerAidSharePercent","PowerAiD share percentage"],["existingMaintenance","Existing maintenance / lamp / year"],["newMaintenance","New maintenance / lamp / year"]],Financial:[["contractYears","Contract years"],["interestRate","Interest rate (%)"],["upfrontPayment","Upfront payment"],["energyEscalation","Energy escalation (%)"],["opexEscalation","OPEX escalation (%)"],["discountRate","Discount rate (%)"],["analysisPeriod","Analysis period"]],Freight:[["freightCostPerLamp","Freight cost / lamp"],["freightSalesPerLamp","Freight sales / lamp"]]};
function Assumptions({p,update}){return <div className="cards-grid">{Object.entries(assumptionGroups).map(([title,fields])=><Card title={title} key={title}><div className="form-grid">{title==="Financial"&&<Field label="Financing model" value={p.assumptions.financingModel} onChange={v=>update(["assumptions","financingModel"],v)}><option value="cash">Cash Purchase</option><option value="laas">Lighting as a Service</option></Field>}{fields.map(([k,l])=><Field key={k} label={l} value={p.assumptions[k]} onChange={v=>update(["assumptions",k],v)}/>)}</div></Card>)}</div>}
function Kpis({p,r,t,money,num}){const list=[[t("preliminary"),r.decisionStatus.replace("_","-"),"status"],[t("capex"),money(r.totalCapex)],[t("annualOpex"),money(r.totalAnnualOpex)],[t("monthlyPayment"),money(r.monthlyPayment)],[t("annualNet"),money(r.customerAnnualNetBenefit)],[t("payback"),r.payback==null?t("notAvailable"):`${num(r.payback,1)} ${t("years")}`],[t("npv"),money(r.npv)],[`${t("lifecycle")} – ${r.analysisPeriod} ${t("years")}`,money(r.lifecycleResult)],[t("energyReduction"),formatPercent(r.energyReductionPercent,p.language)],[t("co2Reduction"),`${num(r.co2ReductionKg/1000,1)} t`]];return <div className="kpis">{list.map(([l,v,c])=><div className={`kpi ${c||""}`} key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>}
function Business({p,r,t,money,num}){return <><div className={`assessment ${r.decisionStatus.toLowerCase()}`}><div><small>{t("preliminary")}</small><h2>{r.decisionStatus.replace("_","-")}</h2></div><p>{t(r.decisionStatus)}</p></div><Kpis p={p} r={r} t={t} money={money} num={num}/><div className="two-col"><Card title={p.language==="it"?"Risultato energetico":"Energy result"}><Breakdown money={v=>`${num(v)} kWh`} rows={[[t("baseline"),1,r.baselineKwh],[t("final"),1,r.finalKwh],[t("ledSaving"),1,r.ledSavingKwh],[t("cloSaving"),1,r.cloSavingKwh],...(r.powerAidEnabled?[[t("powerSaving"),1,r.powerAidSavingKwh]]:[])]}/></Card><Card title={p.language==="it"?"Benefici annuali":"Annual benefits"}><Breakdown money={money} rows={[[p.language==="it"?"Risparmio energia":"Energy saving",1,r.energySaving],[t("maintenanceSaving"),1,r.maintenanceSaving],[p.language==="it"?"Beneficio lordo":"Gross benefit",1,r.grossBenefit],[t("annualOpex"),1,r.totalAnnualOpex],[p.language==="it"?"Pagamento annuo":"Annual payment",1,r.annualPayment],[t("annualNet"),1,r.customerAnnualNetBenefit]]}/></Card></div></>}
function Report({p,r,t,money,num}){return <><div className="report-actions"><p>{p.language==="it"?"Anteprima del rapporto cliente basata sullo stesso motore di calcolo dell’analisi economica.":"Customer report preview based on the same calculation engine as the business case."}</p><button className="primary" onClick={()=>generateCustomerPdf(p,r)}>{t("generate")}</button></div><div className="report-preview"><div className="report-head"><b>VIMALUX Intelligence</b><h2>{p.language==="it"?"Studio Preliminare di Fattibilità Economica":"Preliminary Business Case"}</h2><span>{p.project.businessCaseId} · {p.customer.name||"—"} · {p.project.date}</span></div><h3>{p.language==="it"?"Sintesi Esecutiva":"Executive Summary"}</h3><Kpis p={p} r={r} t={t} money={money} num={num}/><p className="conclusion">{t(r.decisionStatus)}</p><h3>{p.language==="it"?"Flusso di cassa cliente":"Customer cash flow"}</h3><CashTable p={p} r={r} money={money}/><p className="disclaimer">{p.language==="it"?"Questa analisi rappresenta una valutazione preliminare basata su quantità aggregate, potenze medie e ipotesi commerciali. I dati definitivi saranno sviluppati tramite VIMALUX Planner.":"This analysis is a preliminary assessment based on aggregated quantities, average wattages and commercial assumptions. Final data will be developed through VIMALUX Planner."}</p></div></>}
function CashTable({p,r,money}){return <div className="table-scroll"><table><thead><tr>{[p.language==="it"?"Anno":"Year",p.language==="it"?"Beneficio lordo":"Gross benefit","OPEX",p.language==="it"?"Pagamento":"Payment",p.language==="it"?"Flusso netto":"Net cash flow",p.language==="it"?"Cumulato":"Cumulative"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{r.cashFlowRows.map(x=><tr key={x.year}><td>{x.year}</td><td>{money(x.grossBenefit)}</td><td>{money(x.opex)}</td><td>{money(x.payment)}</td><td>{money(x.netCashFlow)}</td><td>{money(x.cumulative)}</td></tr>)}</tbody></table></div>}
function Projects({list,activeId,select,create,t}){return <Card title={t("projects")}><div className="project-list">{list.map(p=><button key={p.id} className={p.id===activeId?"selected":""} onClick={()=>select(p.id)}><strong>{p.project.name}</strong><span>{p.customer.name||"—"}</span><small>{p.project.businessCaseId}</small></button>)}</div><button className="primary" onClick={create}>+ {list[0].language==="it"?"Nuovo progetto":"New project"}</button></Card>}
function Catalogue({p,update}){
  const it=p.language==="it";
  const addLed=()=>update(["catalogue","led"],[...p.catalogue.led,{id:`led-${uid()}`,brand:"",name:it?"Nuovo prodotto LED":"New LED product",wattage:0,lumen:0,costPrice:0,salesPrice:0,active:true}]);
  const addSmart=()=>update(["catalogue","smart"],[...p.catalogue.smart,{id:`smart-${uid()}`,brand:"",name:it?"Nuovo prodotto Smart":"New Smart product",type:"LCU",costPrice:0,salesPrice:0,implementationCost:0,implementationSalesPrice:0,annualCost:0,annualSalesPrice:0,active:true}]);
  const remove=(kind,index)=>{if(confirm(it?"Eliminare questo prodotto dal catalogo?":"Delete this product from the catalogue?"))update(["catalogue",kind],p.catalogue[kind].filter((_,i)=>i!==index))};
  const renderLed=<div className="table-scroll"><table><thead><tr>{["Brand",it?"Prodotto":"Product","W","lm",it?"Costo":"Cost",it?"Prezzo standard":"Standard sales",it?"Attivo":"Active",""].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{p.catalogue.led.map((x,i)=><tr key={x.id}><td><input value={x.brand} onChange={e=>update(["catalogue","led",i,"brand"],e.target.value)}/></td><td><input value={x.name} onChange={e=>update(["catalogue","led",i,"name"],e.target.value)}/></td><td><input value={x.wattage} onChange={e=>update(["catalogue","led",i,"wattage"],e.target.value)}/></td><td><input value={x.lumen} onChange={e=>update(["catalogue","led",i,"lumen"],e.target.value)}/></td><td><input value={x.costPrice} onChange={e=>update(["catalogue","led",i,"costPrice"],e.target.value)}/></td><td><input value={x.salesPrice} onChange={e=>update(["catalogue","led",i,"salesPrice"],e.target.value)}/></td><td><input type="checkbox" checked={x.active} onChange={e=>update(["catalogue","led",i,"active"],e.target.checked)}/></td><td><button className="danger" onClick={()=>remove("led",i)}>{it?"Elimina":"Delete"}</button></td></tr>)}</tbody></table></div>;
  const renderSmart=<div className="table-scroll"><table><thead><tr>{["Brand",it?"Prodotto":"Product",it?"Tipo":"Type",it?"Costo":"Cost",it?"Prezzo standard":"Standard sales",it?"Costo implementazione":"Implementation cost",it?"Prezzo implementazione":"Implementation sales",it?"Costo annuo":"Annual cost",it?"Prezzo annuo cliente":"Annual customer sales",it?"Attivo":"Active",""].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{p.catalogue.smart.map((x,i)=><tr key={x.id}><td><input value={x.brand} onChange={e=>update(["catalogue","smart",i,"brand"],e.target.value)}/></td><td><input value={x.name} onChange={e=>update(["catalogue","smart",i,"name"],e.target.value)}/></td><td><select value={x.type} onChange={e=>update(["catalogue","smart",i,"type"],e.target.value)}>{["LCU","Gateway","Antenna","Energy Meter","Other"].map(type=><option key={type} value={type}>{type}</option>)}</select></td><td><input value={x.costPrice} onChange={e=>update(["catalogue","smart",i,"costPrice"],e.target.value)}/></td><td><input value={x.salesPrice} onChange={e=>update(["catalogue","smart",i,"salesPrice"],e.target.value)}/></td><td><input value={x.implementationCost} onChange={e=>update(["catalogue","smart",i,"implementationCost"],e.target.value)}/></td><td><input value={x.implementationSalesPrice} onChange={e=>update(["catalogue","smart",i,"implementationSalesPrice"],e.target.value)}/></td><td><input value={x.annualCost} onChange={e=>update(["catalogue","smart",i,"annualCost"],e.target.value)}/></td><td><input value={x.annualSalesPrice} onChange={e=>update(["catalogue","smart",i,"annualSalesPrice"],e.target.value)}/></td><td><input type="checkbox" checked={x.active} onChange={e=>update(["catalogue","smart",i,"active"],e.target.checked)}/></td><td><button className="danger" onClick={()=>remove("smart",i)}>{it?"Elimina":"Delete"}</button></td></tr>)}</tbody></table></div>;
  return <><Card title="LED">{renderLed}<button className="primary" onClick={addLed}>+ {it?"Nuovo prodotto LED":"New LED product"}</button></Card><Card title="Smart Lighting">{renderSmart}<button className="primary" onClick={addSmart}>+ {it?"Nuovo prodotto Smart":"New Smart product"}</button></Card></>
}
function Admin({reset,t}){return <Card title={t("priceAdmin")}><p>{t("catalogue")} · {t("projects")}</p><button className="danger" onClick={reset}>{t("reset")}</button></Card>}
