import React,{useEffect,useMemo,useState}from"react";
import{jsPDF}from"jspdf";
import autoTable from"jspdf-autotable";

const NF0=new Intl.NumberFormat("it-IT",{maximumFractionDigits:0});
const NF2=new Intl.NumberFormat("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2});
const EUR0=v=>`${NF0.format(Number(v)||0)} €`;
const EUR2=v=>`${NF2.format(Number(v)||0)} €`;
const NUM=v=>{const s=String(v??"").trim().replace(/\s/g,"");if(!s)return 0;if(s.includes(","))return Number(s.replace(/\./g,"").replace(",","."))||0;return Number(s)||0};
const PMT=(p,r,y)=>{const n=Math.max(1,Math.round(NUM(y)*12)),m=NUM(r)/1200;return m===0?p/n:p*m*Math.pow(1+m,n)/(Math.pow(1+m,n)-1)};

const DEFAULT_LED=[
{id:"manta30",brand:"Aiko",name:"MANTA 30",watt:30,lumen:4800,cost:57,sales:89,active:true},
{id:"manta40",brand:"Aiko",name:"MANTA 40",watt:40,lumen:6400,cost:57,sales:95,active:true},
{id:"enby30",brand:"Elementi",name:"ENBY 30",watt:30,lumen:4800,cost:192,sales:220,active:true},
{id:"enby40",brand:"Elementi",name:"ENBY 40",watt:40,lumen:6400,cost:192,sales:220,active:true},
{id:"enby60",brand:"Elementi",name:"ENBY 60",watt:60,lumen:9600,cost:192,sales:220,active:true}
];
const DEFAULT_SMART=[
{id:"datek-partner",brand:"Datek",name:"Datek Zhaga LCU_PARTNER",type:"LCU",cost:35,sales:48,implementationCost:4,implementationSales:6,annualCost:3.42,annualSales:4,active:true},
{id:"gateway-lx9",brand:"Datek",name:"DLC Gateway IoT LX9",type:"Gateway",cost:505,sales:550,implementationCost:0,implementationSales:0,annualCost:0,annualSales:6,active:true},
{id:"antenna",brand:"Datek",name:"LTE/GNSS/Zigbee antenna",type:"Antenna",cost:93,sales:104,implementationCost:0,implementationSales:0,annualCost:0,annualSales:0,active:true},
{id:"meter",brand:"Schneider",name:"iEM3150 energy meter",type:"Meter",cost:328,sales:365,implementationCost:0,implementationSales:0,annualCost:0,annualSales:0,active:true}
];
const DEFAULTS={burningHours:4200,energyPrice:.29,energyEscalationPct:1.5,maintenanceOld:25,maintenanceNew:15,co2KgPerKwh:.233,cloPct:15,powerAidPct:40,powerAidSharePct:10,powerAidInternalCostPerLamp:0,discountRatePct:6,analysisYears:20,sapFactor:1.2,mhFactor:1.15,mercuryFactor:1.15,freightCostPerLamp:11,freightSalesPerLamp:11};
const blankProject=(name="Comune di San Fele")=>({
 id:`p-${Date.now()}`,
 customer:{name,province:"",region:"",country:"Italy",contact:"",title:"",email:"",phone:""},
 project:{name:"Preliminary Streetlight Business Case",businessCaseId:`BC-${new Date().getFullYear()}-${String(Date.now()).slice(-4)}`,salesPerson:"Luciano Grosso",date:new Date().toISOString().slice(0,10),currency:"EUR",language:"it"},
 groups:[{id:`g-${Date.now()}`,label:"Street lighting",quantity:100,technology:"SAP",existingWatt:100,ledId:"manta40",smart:true,powerAid:true,ledOverride:null}],
 solution:{smartEnabled:true,cmsEnabled:true,powerAidEnabled:true,lcuId:"datek-partner",gatewayId:"gateway-lx9",gatewayQty:2,antennaId:"antenna",antennaQty:2,meterId:"meter",meterQty:2},
 finance:{model:"Lighting as a Service",years:10,interestRate:8,upfront:0},
 assumptions:{...DEFAULTS},
 overrides:{}
});

export default function AppBusinessCaseV1(){
 const[led,setLed]=useState(()=>JSON.parse(localStorage.getItem("vml-bc-led")||"null")||DEFAULT_LED);
 const[smart,setSmart]=useState(()=>JSON.parse(localStorage.getItem("vml-bc-smart")||"null")||DEFAULT_SMART);
 const[projects,setProjects]=useState(()=>JSON.parse(localStorage.getItem("vml-bc-projects")||"null")||[blankProject()]);
 const[activeId,setActiveId]=useState(()=>localStorage.getItem("vml-bc-active")||"");
 const[tab,setTab]=useState("overview");
 const active=projects.find(p=>p.id===activeId)||projects[0];
 useEffect(()=>{if(active&&!activeId)setActiveId(active.id)},[active,activeId]);
 useEffect(()=>localStorage.setItem("vml-bc-led",JSON.stringify(led)),[led]);
 useEffect(()=>localStorage.setItem("vml-bc-smart",JSON.stringify(smart)),[smart]);
 useEffect(()=>localStorage.setItem("vml-bc-projects",JSON.stringify(projects)),[projects]);
 useEffect(()=>{if(activeId)localStorage.setItem("vml-bc-active",activeId)},[activeId]);
 const patch=p=>setProjects(xs=>xs.map(x=>x.id===active.id?{...x,...p}:x));
 const setCustomer=(k,v)=>patch({customer:{...active.customer,[k]:v}});
 const setProject=(k,v)=>patch({project:{...active.project,[k]:v}});
 const setSolution=(k,v)=>patch({solution:{...active.solution,[k]:v}});
 const setFinance=(k,v)=>patch({finance:{...active.finance,[k]:v}});
 const setAss=(k,v)=>patch({assumptions:{...active.assumptions,[k]:v}});
 const setGroups=groups=>patch({groups});
 const setOverride=(id,k,v)=>patch({overrides:{...active.overrides,[id]:{...(active.overrides[id]||{}),[k]:v}}});
 const ledMap=useMemo(()=>new Map(led.map(x=>[x.id,x])),[led]);
 const smartMap=useMemo(()=>new Map(smart.map(x=>[x.id,x])),[smart]);
 const priceOf=(item,key)=>NUM(active.overrides[item?.id]?.[key]??item?.[key]);
 const result=useMemo(()=>{
  const a=active.assumptions,s=active.solution,f=active.finance;
  let qty=0,baselineKwh=0,ledKwh=0,ledCapex=0,smartQty=0;
  for(const g of active.groups){const q=NUM(g.quantity),w=NUM(g.existingWatt),fac=g.technology==="SAP"?NUM(a.sapFactor):g.technology==="MH"?NUM(a.mhFactor):g.technology==="Mercury"?NUM(a.mercuryFactor):1;const p=ledMap.get(g.ledId);qty+=q;baselineKwh+=q*w*fac*NUM(a.burningHours)/1000;ledKwh+=q*NUM(p?.watt)*NUM(a.burningHours)/1000;ledCapex+=q*NUM(g.ledOverride??priceOf(p,"sales"));if(g.smart&&s.smartEnabled)smartQty+=q;}
  const ledSavingKwh=Math.max(0,baselineKwh-ledKwh);
  const cloSavingKwh=s.smartEnabled?ledKwh*NUM(a.cloPct)/100:0;
  const afterClo=Math.max(0,ledKwh-cloSavingKwh);
  const powerAidSavingKwh=s.smartEnabled&&s.powerAidEnabled?afterClo*NUM(a.powerAidPct)/100:0;
  const finalKwh=Math.max(0,afterClo-powerAidSavingKwh);
  const lcu=smartMap.get(s.lcuId),gateway=smartMap.get(s.gatewayId),antenna=smartMap.get(s.antennaId),meter=smartMap.get(s.meterId);
  const smartHardware=smartQty*priceOf(lcu,"sales");
  const implementation=smartQty*priceOf(lcu,"implementationSales");
  const gatewayCapex=NUM(s.gatewayQty)*priceOf(gateway,"sales");
  const antennaCapex=NUM(s.antennaQty)*priceOf(antenna,"sales");
  const meterCapex=NUM(s.meterQty)*priceOf(meter,"sales");
  const freight=qty*NUM(a.freightSalesPerLamp);
  const capex=ledCapex+smartHardware+implementation+gatewayCapex+antennaCapex+meterCapex+freight;
  const cms=s.cmsEnabled&&s.smartEnabled?smartQty*priceOf(lcu,"annualSales"):0;
  const gatewayOpex=s.cmsEnabled&&s.smartEnabled?NUM(s.gatewayQty)*priceOf(gateway,"annualSales"):0;
  const powerAidGross=powerAidSavingKwh*NUM(a.energyPrice);
  const powerAidFee=s.powerAidEnabled?powerAidGross*NUM(a.powerAidSharePct)/100:0;
  const annualOpex=cms+gatewayOpex+powerAidFee;
  const energySaving=(baselineKwh-finalKwh)*NUM(a.energyPrice);
  const maintenanceSaving=Math.max(0,qty*(NUM(a.maintenanceOld)-NUM(a.maintenanceNew)));
  const grossBenefit=energySaving+maintenanceSaving;
  const operatingNet=grossBenefit-annualOpex;
  const monthly=f.model==="Cash Purchase"?0:PMT(Math.max(0,capex-NUM(f.upfront)),f.interestRate,f.years);
  const annualPayment=monthly*12;
  const customerNet=operatingNet-annualPayment;
  let npv=-capex,cumulative=-NUM(f.upfront);const rows=[];for(let y=1;y<=NUM(a.analysisYears);y++){const idx=Math.pow(1+NUM(a.energyEscalationPct)/100,y-1);const benefit=grossBenefit*idx,opex=annualOpex*idx,payment=y<=NUM(f.years)?annualPayment:0,net=benefit-opex-payment;cumulative+=net;rows.push({year:y,benefit,opex,payment,net,cumulative});npv+=net/Math.pow(1+NUM(a.discountRatePct)/100,y)}
  const payback=operatingNet>0?capex/operatingNet:0;
  const lifecycle=rows.at(-1)?.cumulative||0;
  const energyReductionPct=baselineKwh?100*(baselineKwh-finalKwh)/baselineKwh:0;
  const co2Tonnes=(baselineKwh-finalKwh)*NUM(a.co2KgPerKwh)/1000;
  const status=customerNet>0&&payback<=8?"GO":customerNet>0?"REVIEW":"NO-GO";
  return{qty,baselineKwh,ledKwh,finalKwh,ledSavingKwh,cloSavingKwh,powerAidSavingKwh,ledCapex,smartHardware,implementation,gatewayCapex,antennaCapex,meterCapex,freight,capex,cms,gatewayOpex,powerAidFee,annualOpex,energySaving,maintenanceSaving,grossBenefit,operatingNet,monthly,annualPayment,customerNet,npv,payback,lifecycle,energyReductionPct,co2Tonnes,status,rows,smartQty};
 },[active,ledMap,smartMap]);

 function generatePdf(){
  const d=new jsPDF({unit:"mm",format:"a4"});const dark=[16,56,64],green=[200,239,85],muted=[96,118,124];
  const title=(t,y)=>{d.setTextColor(...dark);d.setFontSize(16);d.setFont("helvetica","bold");d.text(t,14,y)};
  d.setFillColor(...dark);d.rect(0,0,210,24,"F");d.setTextColor(255,255,255);d.setFontSize(18);d.setFont("helvetica","bold");d.text("VIMALUX Intelligence",14,15);d.setFontSize(9);d.text("Preliminary Business Case",145,10);d.text(active.project.businessCaseId,145,15);d.text(active.customer.name,145,20);d.setFillColor(...green);d.rect(0,24,210,2,"F");
  title("Executive summary",36);
  autoTable(d,{startY:41,theme:"grid",styles:{fontSize:8,cellPadding:3},headStyles:{fillColor:dark},head:[["Decision","CAPEX","Annual net benefit","Payback","Energy reduction","CO₂ reduction"]],body:[[result.status,EUR0(result.capex),EUR0(result.customerNet),`${result.payback.toFixed(1)} years`,`${NF2.format(result.energyReductionPct)}%`,`${NF2.format(result.co2Tonnes)} t/y`]]});
  const y1=d.lastAutoTable.finalY+6;title("Customer and project",y1);
  autoTable(d,{startY:y1+4,theme:"plain",styles:{fontSize:8,cellPadding:1.5},columnStyles:{0:{fontStyle:"bold",textColor:muted}},body:[["Customer",active.customer.name],["Province / Region",`${active.customer.province||"-"} / ${active.customer.region||"-"}`],["Contact",`${active.customer.contact||"-"} · ${active.customer.email||"-"}`],["Project",active.project.name],["Sales person",active.project.salesPerson],["Date",active.project.date]]});
  const y2=d.lastAutoTable.finalY+5;title("Existing installation and proposed solution",y2);
  const groups=active.groups.map(g=>{const p=ledMap.get(g.ledId);return[g.label,NF0.format(NUM(g.quantity)),g.technology,`${NF0.format(NUM(g.existingWatt))} W`,`${p?.name||"-"} · ${p?.watt||0} W`,g.smart&&active.solution.smartEnabled?"Yes":"No",g.powerAid&&active.solution.powerAidEnabled?"Yes":"No"]});
  autoTable(d,{startY:y2+4,theme:"grid",styles:{fontSize:7,cellPadding:2},headStyles:{fillColor:dark},head:[["Group","Qty","Technology","Existing","Proposed LED","Smart","PowerAiD"]],body:groups});
  const y3=d.lastAutoTable.finalY+5;title("Energy and financial result",y3);
  autoTable(d,{startY:y3+4,theme:"grid",styles:{fontSize:8,cellPadding:2.5},headStyles:{fillColor:dark},body:[["Baseline consumption",`${NF0.format(result.baselineKwh)} kWh/year`],["Final consumption",`${NF0.format(result.finalKwh)} kWh/year`],["Energy saving",EUR0(result.energySaving)],["Maintenance saving",EUR0(result.maintenanceSaving)],["Annual OPEX",EUR0(result.annualOpex)],["Monthly payment",EUR2(result.monthly)],["NPV",EUR0(result.npv)],["Lifecycle result",EUR0(result.lifecycle)]]});
  d.addPage();title("CAPEX and OPEX breakdown",18);
  autoTable(d,{startY:23,theme:"grid",styles:{fontSize:8,cellPadding:2.5},headStyles:{fillColor:dark},head:[["CAPEX component","Amount","Annual OPEX component","Amount"]],body:[["LED luminaires",EUR0(result.ledCapex),"CMS",EUR0(result.cms)],["Smart hardware",EUR0(result.smartHardware),"Gateway OPEX",EUR0(result.gatewayOpex)],["Implementation",EUR0(result.implementation),"PowerAiD fee",EUR0(result.powerAidFee)],["Gateways",EUR0(result.gatewayCapex),"Total annual OPEX",EUR0(result.annualOpex)],["Antennas",EUR0(result.antennaCapex),"",""] ,["Meters",EUR0(result.meterCapex),"",""],["Freight",EUR0(result.freight),"",""],["Total CAPEX",EUR0(result.capex),"",""]]});
  const y4=d.lastAutoTable.finalY+6;title("Customer cash flow",y4);
  autoTable(d,{startY:y4+4,theme:"striped",styles:{fontSize:7,cellPadding:2},headStyles:{fillColor:dark},head:[["Year","Benefit","OPEX","Payment","Net","Cumulative"]],body:result.rows.slice(0,NUM(active.finance.years)).map(r=>[r.year,EUR0(r.benefit),EUR0(r.opex),EUR0(r.payment),EUR0(r.net),EUR0(r.cumulative)]),pageBreak:"auto",rowPageBreak:"avoid",showHead:"everyPage"});
  const pages=d.getNumberOfPages();for(let i=1;i<=pages;i++){d.setPage(i);d.setFontSize(7);d.setTextColor(...muted);d.text("Preliminary calculation based on aggregated quantities and wattages. Final engineering, geo-positioning, photometric design and product assignment are completed in VIMALUX Planner.",14,287,{maxWidth:175});d.text(`${i}/${pages}`,195,292,{align:"right"})}
  d.save(`${active.project.businessCaseId}_${active.customer.name.replace(/\s+/g,"_")}.pdf`);
 }

 const nav=[["projects","Projects"],["overview","Customer & Project"],["lighting","Existing Lighting"],["solution","Solution"],["pricing","Project Pricing"],["assumptions","Assumptions"],["business","Business Case"],["report","Report"],["admin","Admin"]];
 return <div style={S.shell}><aside style={S.side}><div style={S.brand}>VIMALUX<br/>INTELLIGENCE</div><div style={S.badge}><small>ACTIVE PROJECT</small><b>{active.customer.name}</b><span>{active.project.businessCaseId}</span></div>{nav.map(([id,l])=><button key={id} style={tab===id?S.on:S.nav} onClick={()=>setTab(id)}>{l}</button>)}</aside><main style={S.main}><header style={S.header}><div><small>PRELIMINARY BUSINESS CASE</small><h1>{tab==="projects"?"Projects":active.customer.name}</h1></div>{tab!=="report"&&<button style={S.primary} onClick={()=>setTab("report")}>Review report</button>}</header>
 {tab==="projects"&&<Card title="Projects"><button style={S.primary} onClick={()=>{const p=blankProject("New customer");setProjects(x=>[...x,p]);setActiveId(p.id);setTab("overview")}}>＋ New business case</button><div style={S.cards}>{projects.map(p=><button key={p.id} style={p.id===active.id?S.projectOn:S.project} onClick={()=>{setActiveId(p.id);setTab("overview")}}><b>{p.customer.name}</b><span>{p.project.businessCaseId}</span></button>)}</div></Card>}
 {tab==="overview"&&<div style={S.grid}><Card title="Customer"><Text label="Customer / municipality" value={active.customer.name} commit={v=>setCustomer("name",v)}/><Text label="Province" value={active.customer.province} commit={v=>setCustomer("province",v)}/><Text label="Region" value={active.customer.region} commit={v=>setCustomer("region",v)}/><Text label="Country" value={active.customer.country} commit={v=>setCustomer("country",v)}/><Text label="Contact person" value={active.customer.contact} commit={v=>setCustomer("contact",v)}/><Text label="Title" value={active.customer.title} commit={v=>setCustomer("title",v)}/><Text label="Email" value={active.customer.email} commit={v=>setCustomer("email",v)}/><Text label="Phone" value={active.customer.phone} commit={v=>setCustomer("phone",v)}/></Card><Card title="Project"><Text label="Project name" value={active.project.name} commit={v=>setProject("name",v)}/><Text label="Business Case ID" value={active.project.businessCaseId} commit={v=>setProject("businessCaseId",v)}/><Text label="Sales person" value={active.project.salesPerson} commit={v=>setProject("salesPerson",v)}/><Text label="Date" value={active.project.date} commit={v=>setProject("date",v)}/><Row l="Current decision" v={result.status}/><Row l="CAPEX" v={EUR0(result.capex)}/><Row l="Annual customer net" v={EUR0(result.customerNet)}/></Card></div>}
 {tab==="lighting"&&<Card title="Existing Lighting"><p style={S.muted}>Enter aggregated quantities, existing technology and wattage. Geo-positioning is not required.</p><table style={S.table}><thead><tr><th>Group</th><th>Quantity</th><th>Technology</th><th>Existing W</th><th>Proposed LED</th><th>Smart</th><th>PowerAiD</th><th></th></tr></thead><tbody>{active.groups.map(g=><tr key={g.id}><td><Text value={g.label} commit={v=>setGroups(active.groups.map(x=>x.id===g.id?{...x,label:v}:x))}/></td><td><NumberBox value={g.quantity} commit={v=>setGroups(active.groups.map(x=>x.id===g.id?{...x,quantity:v}:x))}/></td><td><select value={g.technology} onChange={e=>setGroups(active.groups.map(x=>x.id===g.id?{...x,technology:e.target.value}:x))}><option>SAP</option><option>MH</option><option>Mercury</option><option>LED</option><option>Unknown</option></select></td><td><NumberBox value={g.existingWatt} commit={v=>setGroups(active.groups.map(x=>x.id===g.id?{...x,existingWatt:v}:x))}/></td><td><select value={g.ledId} onChange={e=>setGroups(active.groups.map(x=>x.id===g.id?{...x,ledId:e.target.value}:x))}>{led.filter(x=>x.active).map(p=><option key={p.id} value={p.id}>{p.name} · {p.watt}W</option>)}</select></td><td><input type="checkbox" checked={g.smart} onChange={e=>setGroups(active.groups.map(x=>x.id===g.id?{...x,smart:e.target.checked}:x))}/></td><td><input type="checkbox" checked={g.powerAid} onChange={e=>setGroups(active.groups.map(x=>x.id===g.id?{...x,powerAid:e.target.checked}:x))}/></td><td><button onClick={()=>setGroups(active.groups.filter(x=>x.id!==g.id))}>×</button></td></tr>)}</tbody></table><button style={S.secondary} onClick={()=>setGroups([...active.groups,{id:`g-${Date.now()}`,label:"New group",quantity:1,technology:"SAP",existingWatt:100,ledId:led[0]?.id,smart:true,powerAid:true,ledOverride:null}])}>＋ Add group</button></Card>}
 {tab==="solution"&&<div style={S.grid}><Card title="Solution selection"><Toggle label="Smart Lighting" value={active.solution.smartEnabled} change={v=>setSolution("smartEnabled",v)}/><Toggle label="CMS & connectivity" value={active.solution.cmsEnabled} change={v=>setSolution("cmsEnabled",v)}/><Toggle label="PowerAiD adaptive dimming" value={active.solution.powerAidEnabled} change={v=>setSolution("powerAidEnabled",v)}/><Select label="LCU controller" value={active.solution.lcuId} change={v=>setSolution("lcuId",v)} options={smart.filter(x=>x.type==="LCU"&&x.active).map(x=>[x.id,x.name])}/></Card><Card title="Additional equipment"><Select label="Gateway" value={active.solution.gatewayId} change={v=>setSolution("gatewayId",v)} options={smart.filter(x=>x.type==="Gateway"&&x.active).map(x=>[x.id,x.name])}/><NumberBox label="Gateway quantity" value={active.solution.gatewayQty} commit={v=>setSolution("gatewayQty",v)}/><Select label="Antenna" value={active.solution.antennaId} change={v=>setSolution("antennaId",v)} options={smart.filter(x=>x.type==="Antenna"&&x.active).map(x=>[x.id,x.name])}/><NumberBox label="Antenna quantity" value={active.solution.antennaQty} commit={v=>setSolution("antennaQty",v)}/><Select label="Energy meter" value={active.solution.meterId} change={v=>setSolution("meterId",v)} options={smart.filter(x=>x.type==="Meter"&&x.active).map(x=>[x.id,x.name])}/><NumberBox label="Meter quantity" value={active.solution.meterQty} commit={v=>setSolution("meterQty",v)}/></Card></div>}
 {tab==="pricing"&&<Card title="Project Pricing"><p style={S.muted}>Catalogue prices are copied into the project. Override sales prices here without changing master data.</p><table style={S.table}><thead><tr><th>Product</th><th>Type</th><th>Cost</th><th>Catalogue sales</th><th>Project sales</th><th>Margin</th></tr></thead><tbody>{[...led.filter(p=>active.groups.some(g=>g.ledId===p.id)),...smart.filter(p=>[active.solution.lcuId,active.solution.gatewayId,active.solution.antennaId,active.solution.meterId].includes(p.id))].map(p=>{const sales=priceOf(p,"sales"),cost=priceOf(p,"cost"),margin=sales?100*(sales-cost)/sales:0;return <tr key={p.id}><td>{p.name}</td><td>{p.type||"LED"}</td><td>{EUR2(cost)}</td><td>{EUR2(p.sales)}</td><td><NumberBox value={sales} commit={v=>setOverride(p.id,"sales",v)}/></td><td>{NF2.format(margin)}%</td></tr>})}</tbody></table></Card>}
 {tab==="assumptions"&&<div style={S.grid}><Card title="Technical assumptions"><NumberBox label="Burning hours / year" value={active.assumptions.burningHours} commit={v=>setAss("burningHours",v)}/><NumberBox label="Energy price €/kWh" value={active.assumptions.energyPrice} commit={v=>setAss("energyPrice",v)}/><NumberBox label="CLO saving %" value={active.assumptions.cloPct} commit={v=>setAss("cloPct",v)}/><NumberBox label="PowerAiD additional saving % after CLO" value={active.assumptions.powerAidPct} commit={v=>setAss("powerAidPct",v)}/><NumberBox label="Existing maintenance / lamp / year" value={active.assumptions.maintenanceOld} commit={v=>setAss("maintenanceOld",v)}/><NumberBox label="New maintenance / lamp / year" value={active.assumptions.maintenanceNew} commit={v=>setAss("maintenanceNew",v)}/></Card><Card title="Commercial assumptions"><Select label="Business model" value={active.finance.model} change={v=>setFinance("model",v)} options={[["Cash Purchase","Cash Purchase"],["Leasing","Leasing"],["Lighting as a Service","Lighting as a Service"],["ESCO","ESCO"],["PPP","PPP"]]}/><NumberBox label="Contract years" value={active.finance.years} commit={v=>setFinance("years",v)}/><NumberBox label="Customer interest %" value={active.finance.interestRate} commit={v=>setFinance("interestRate",v)}/><NumberBox label="Upfront payment" value={active.finance.upfront} commit={v=>setFinance("upfront",v)}/><NumberBox label="PowerAiD share of extra saving %" value={active.assumptions.powerAidSharePct} commit={v=>setAss("powerAidSharePct",v)}/><NumberBox label="Discount rate %" value={active.assumptions.discountRatePct} commit={v=>setAss("discountRatePct",v)}/></Card></div>}
 {tab==="business"&&<><div style={S.kpis}><Kpi t="Decision" v={result.status}/><Kpi t="CAPEX" v={EUR0(result.capex)}/><Kpi t="Annual net benefit" v={EUR0(result.customerNet)}/><Kpi t="Monthly payment" v={EUR2(result.monthly)}/><Kpi t="Payback" v={`${result.payback.toFixed(1)} years`}/><Kpi t="Energy reduction" v={`${NF2.format(result.energyReductionPct)}%`}/></div><div style={S.grid}><Card title="Energy & OPEX"><Row l="Baseline consumption" v={`${NF0.format(result.baselineKwh)} kWh`}/><Row l="Final consumption" v={`${NF0.format(result.finalKwh)} kWh`}/><Row l="Energy saving" v={EUR0(result.energySaving)}/><Row l="Maintenance saving" v={EUR0(result.maintenanceSaving)}/><Row l="Annual OPEX" v={EUR0(result.annualOpex)}/><Row l="CO₂ reduction" v={`${NF2.format(result.co2Tonnes)} t/y`}/></Card><Card title="Investment result"><Row l="NPV" v={EUR0(result.npv)}/><Row l="Lifecycle result" v={EUR0(result.lifecycle)}/><Row l="Annual payment" v={EUR0(result.annualPayment)}/><Row l="Operating net before finance" v={EUR0(result.operatingNet)}/></Card></div></>}
 {tab==="report"&&<Card title="Preliminary Business Case Report"><p style={S.muted}>Customer-ready PDF generated from the current customer, product, pricing, solution and financial data.</p><div style={S.kpis}><Kpi t="Decision" v={result.status}/><Kpi t="CAPEX" v={EUR0(result.capex)}/><Kpi t="Annual net benefit" v={EUR0(result.customerNet)}/><Kpi t="Payback" v={`${result.payback.toFixed(1)} years`}/></div><button style={S.primary} onClick={generatePdf}>Generate business case PDF</button></Card>}
 {tab==="admin"&&<><Card title="LED Product Catalogue"><EditableTable items={led} setItems={setLed} type="LED"/></Card><Card title="Smart Lighting Catalogue"><EditableTable items={smart} setItems={setSmart} type="SMART"/></Card></>}
 </main></div>
}

function EditableTable({items,setItems,type}){const add=()=>setItems([...items,{id:`x-${Date.now()}`,brand:"",name:"New product",watt:0,lumen:0,type:type==="SMART"?"LCU":undefined,cost:0,sales:0,implementationCost:0,implementationSales:0,annualCost:0,annualSales:0,active:true}]);return <><table style={S.table}><thead><tr><th>Name</th><th>Brand</th>{type==="LED"?<><th>Watt</th><th>Lumen</th></>:<><th>Type</th><th>Impl. sales</th><th>Annual sales</th></>}<th>Cost</th><th>Sales</th><th>Active</th><th></th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><Text value={p.name} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,name:v}:x))}/></td><td><Text value={p.brand} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,brand:v}:x))}/></td>{type==="LED"?<><td><NumberBox value={p.watt} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,watt:v}:x))}/></td><td><NumberBox value={p.lumen} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,lumen:v}:x))}/></td></>:<><td><select value={p.type} onChange={e=>setItems(items.map(x=>x.id===p.id?{...x,type:e.target.value}:x))}><option>LCU</option><option>Gateway</option><option>Antenna</option><option>Meter</option><option>Other</option></select></td><td><NumberBox value={p.implementationSales} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,implementationSales:v}:x))}/></td><td><NumberBox value={p.annualSales} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,annualSales:v}:x))}/></td></>}<td><NumberBox value={p.cost} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,cost:v}:x))}/></td><td><NumberBox value={p.sales} commit={v=>setItems(items.map(x=>x.id===p.id?{...x,sales:v}:x))}/></td><td><input type="checkbox" checked={p.active} onChange={e=>setItems(items.map(x=>x.id===p.id?{...x,active:e.target.checked}:x))}/></td><td><button onClick={()=>setItems(items.filter(x=>x.id!==p.id))}>×</button></td></tr>)}</tbody></table><button style={S.secondary} onClick={add}>＋ Add product</button></>}
function Card({title,children}){return <section style={S.card}><h2>{title}</h2>{children}</section>}
function Text({label,value,commit}){const[v,setV]=useState(value??"");useEffect(()=>setV(value??""),[value]);return <label style={S.field}>{label&&<span>{label}</span>}<input value={v} onChange={e=>setV(e.target.value)} onBlur={()=>commit?.(v)} onKeyDown={e=>{if(e.key==="Enter")commit?.(v)}}/></label>}
function NumberBox({label,value,commit}){const[v,setV]=useState(String(value??""));useEffect(()=>setV(String(value??"")),[value]);return <label style={S.field}>{label&&<span>{label}</span>}<input value={v} onChange={e=>setV(e.target.value)} onBlur={()=>{const x=NUM(v);setV(String(x));commit?.(x)}} onKeyDown={e=>{if(e.key==="Enter"){const x=NUM(v);setV(String(x));commit?.(x)}}}/></label>}
function Select({label,value,change,options}){return <label style={S.field}>{label&&<span>{label}</span>}<select value={value} onChange={e=>change(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Toggle({label,value,change}){return <label style={S.toggle}><span>{label}</span><input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/></label>}
function Row({l,v}){return <div style={S.row}><span>{l}</span><b>{v}</b></div>}
function Kpi({t,v}){return <div style={S.kpi}><span>{t}</span><b>{v}</b></div>}
const S={shell:{display:"flex",minHeight:"100vh",fontFamily:"Arial,sans-serif",background:"#f4f7f8",color:"#103840"},side:{width:250,background:"#0a3438",color:"white",padding:20,boxSizing:"border-box"},brand:{fontSize:24,fontWeight:900,lineHeight:1.25,marginBottom:28},badge:{background:"#16484d",padding:16,borderRadius:14,display:"grid",gap:6,marginBottom:20},nav:{display:"block",width:"100%",textAlign:"left",padding:"11px 12px",border:0,background:"transparent",color:"white",fontSize:15},on:{display:"block",width:"100%",textAlign:"left",padding:"11px 12px",border:0,borderRadius:10,background:"#c8ef55",color:"#103840",fontWeight:800,fontSize:15},main:{flex:1,padding:28,overflowX:"auto"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24},primary:{background:"#0a3438",color:"white",border:0,borderRadius:10,padding:"13px 20px",fontWeight:800,fontSize:15},secondary:{background:"white",border:"1px solid #b8c8cb",borderRadius:8,padding:"9px 14px",marginTop:12},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:18},card:{background:"white",borderRadius:16,padding:24,boxShadow:"0 8px 24px rgba(14,52,56,.06)",marginBottom:18},field:{display:"grid",gap:6,marginBottom:12,fontWeight:700,fontSize:13},toggle:{display:"flex",justifyContent:"space-between",padding:"12px 0",borderBottom:"1px solid #e5ecee",fontWeight:700},row:{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #e5ecee"},kpis:{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginBottom:18},kpi:{background:"white",border:"1px solid #dbe6e8",borderRadius:14,padding:16,display:"grid",gap:8},table:{width:"100%",borderCollapse:"collapse"},cards:{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginTop:16},project:{padding:16,border:"1px solid #dbe6e8",borderRadius:12,background:"white",display:"grid",gap:6,textAlign:"left"},projectOn:{padding:16,border:"2px solid #0a3438",borderRadius:12,background:"#eff9d8",display:"grid",gap:6,textAlign:"left"},muted:{color:"#647b80"}};
