import React,{useEffect,useMemo,useRef,useState}from"react";
import*as XLSX from"xlsx";
import{auditRowsToManualGroups,calculateManualProject,createManualGroup,recommendProduct}from"./v31ManualProjectEngine.js";

const DEFAULT_PRODUCTS=[
{id:"manta30",name:"MANTA 30",watt:30,lumen:4800,buyPrice:57,sellPrice:89,active:true},
{id:"manta40",name:"MANTA 40",watt:40,lumen:6400,buyPrice:57,sellPrice:95,active:true},
{id:"enby30",name:"ENBY 30",watt:30,lumen:4800,buyPrice:192,sellPrice:220,active:true},
{id:"enby40",name:"ENBY 40",watt:40,lumen:6400,buyPrice:192,sellPrice:220,active:true},
{id:"enby60",name:"ENBY 60",watt:60,lumen:9600,buyPrice:192,sellPrice:220,active:true}
];
const DEFAULT_ASS={energyPrice:.29,burningHours:4200,cloSavingPct:15,powerAidAdditionalSavingPct:40,maintenanceOldPerLamp:25,co2KgPerKwh:.233,sapBallastFactor:1.2,mhBallastFactor:1.15,mercuryBallastFactor:1.15,fluorescentBallastFactor:1.1,ledBallastFactor:1,unknownBallastFactor:1,discountRatePct:2,savingIndexationPct:1.5,analysisYears:20};
const DEFAULT_COM={model:"Lighting as a Service",years:10,interestRate:8,upfront:0,smartEnabled:true,cmsEnabled:true,powerAidEnabled:true,smartHardwareSellPerLamp:48,implementationSellPerLamp:6,cmsSellPerLampYear:4,powerAidPerformanceSharePct:10,gatewayQty:2,gatewaySell:550,gatewayOpex:6,antennaQty:2,antennaSell:104,meterQty:2,meterSell:365,maintenanceAfterPerLamp:15,freightSellPerLamp:0,overallPriceAdjustment:0};
const money0=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:0});
const money2=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",minimumFractionDigits:2,maximumFractionDigits:2});
const num=v=>{const s=String(v??"").trim().replace(/\s/g,"");if(!s)return 0;if(s.includes(","))return Number(s.replace(/\./g,"").replace(",","."))||0;return Number(s)||0};
const payment=(p,r,y)=>{const n=Math.max(1,Math.round(y*12)),m=(r/100)/12;return m===0?p/n:p*m*Math.pow(1+m,n)/(Math.pow(1+m,n)-1)};
const blankProject=(name="Comune di San Fele")=>({id:`p-${Date.now()}`,project:{municipality:name,quotationId:`Q-${new Date().getFullYear()}-${String(Date.now()).slice(-4)}`},assumptions:{...DEFAULT_ASS},commercial:{...DEFAULT_COM},groups:[createManualGroup(1,{label:"Street lighting",quantity:1,existingType:"SAP",existingWatt:70,productId:"manta30",smart:true,powerAid:true,hybrid:false})]});

export default function AppFinalEngine(){
const[products,setProducts]=useState(()=>JSON.parse(localStorage.getItem("vml-final-products")||"null")||DEFAULT_PRODUCTS);
const[projects,setProjects]=useState(()=>JSON.parse(localStorage.getItem("vml-final-projects")||"null")||[blankProject()]);
const[activeId,setActiveId]=useState(()=>localStorage.getItem("vml-final-active")||"");
const[tab,setTab]=useState("overview");const auditRef=useRef(null);
const active=projects.find(x=>x.id===activeId)||projects[0];
useEffect(()=>{if(active&&!activeId)setActiveId(active.id)},[active,activeId]);
useEffect(()=>localStorage.setItem("vml-final-products",JSON.stringify(products)),[products]);
useEffect(()=>localStorage.setItem("vml-final-projects",JSON.stringify(projects)),[projects]);
useEffect(()=>{if(activeId)localStorage.setItem("vml-final-active",activeId)},[activeId]);
const project=active.project,ass=active.assumptions,com=active.commercial,groups=active.groups;
const patch=p=>setProjects(list=>list.map(x=>x.id===active.id?{...x,...p}:x));
const setAss=(k,v)=>patch({assumptions:{...ass,[k]:v}}),setCom=(k,v)=>patch({commercial:{...com,[k]:v}}),setGroups=v=>patch({groups:v});
const activeProducts=useMemo(()=>products.filter(p=>p.active!==false),[products]);
const productMap=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);
const effective=useMemo(()=>groups.map(g=>({...g,smart:com.smartEnabled&&g.smart,powerAid:com.smartEnabled&&com.powerAidEnabled&&g.powerAid})),[groups,com.smartEnabled,com.powerAidEnabled]);
const calc=useMemo(()=>calculateManualProject(effective,ass,activeProducts),[effective,ass,activeProducts]);
const q=useMemo(()=>{const qty=calc.totals.quantity;const lum=groups.reduce((s,g)=>s+num(g.quantity)*num(productMap.get(g.productId)?.sellPrice),0);const smartQty=com.smartEnabled?groups.reduce((s,g)=>s+(g.smart?num(g.quantity):0),0):0;const smart=smartQty*num(com.smartHardwareSellPerLamp);const impl=smartQty*num(com.implementationSellPerLamp);const extra=com.smartEnabled?(num(com.gatewayQty)*num(com.gatewaySell)+num(com.antennaQty)*num(com.antennaSell)+num(com.meterQty)*num(com.meterSell)):0;const freight=qty*num(com.freightSellPerLamp);const capex=lum+smart+impl+extra+freight+num(com.overallPriceAdjustment);const cms=com.cmsEnabled&&com.smartEnabled?smartQty*num(com.cmsSellPerLampYear):0;const gateway=com.cmsEnabled&&com.smartEnabled?num(com.gatewayQty)*num(com.gatewayOpex):0;const powerGross=com.powerAidEnabled?calc.totals.powerAidSavingKwh*num(ass.energyPrice):0;const powerFee=com.powerAidEnabled?powerGross*num(com.powerAidPerformanceSharePct)/100:0;const annualOpex=cms+gateway+powerFee;const maintenance=Math.max(0,qty*(num(ass.maintenanceOldPerLamp)-num(com.maintenanceAfterPerLamp)));const gross=calc.totals.totalEnergySavingValue+maintenance;const beforeFinance=gross-annualOpex;const monthly=com.model==="Cash purchase"?0:payment(Math.max(0,capex-num(com.upfront)),num(com.interestRate),num(com.years));const annualPayment=monthly*12;const net=beforeFinance-annualPayment;let npv=-capex,cumulative=-num(com.upfront);const rows=[];for(let y=1;y<=20;y++){const idx=Math.pow(1+num(ass.savingIndexationPct)/100,y-1);const b=gross*idx,o=annualOpex*idx,p=y<=num(com.years)?annualPayment:0,n=b-o-p;cumulative+=n;rows.push({y,b,o,p,n,cumulative});if(y<=num(com.years))npv+=(b-o)/Math.pow(1+num(ass.discountRatePct)/100,y)}return{qty,capex,annualOpex,gross,beforeFinance,monthly,annualPayment,net,npv,payback:beforeFinance>0?capex/beforeFinance:0,lifecycle:beforeFinance*num(com.years)-capex,powerFee,rows};},[calc,groups,productMap,ass,com]);
async function importAudit(e){const f=e.target.files?.[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer(),{type:"array"}),sh=wb.SheetNames.includes("Luminaire_Audit")?"Luminaire_Audit":wb.SheetNames[0],rows=XLSX.utils.sheet_to_json(wb.Sheets[sh],{defval:""});const n=rows.map((r,i)=>({label:r.Group||r.Name||r.ID||r.Pole_ID||`Group ${i+1}`,quantity:num(r.Quantity||r.Qty||1),existingType:r.Existing_Type||r.Technology||r.Tecnologia||r.Lamp_Type||r.Type||"Unknown",existingWatt:num(r.Existing_Watt||r.Wattage||r.Watt||r.Power)})).filter(r=>r.existingWatt>0);const imported=auditRowsToManualGroups(n,activeProducts);if(imported.length)setGroups(imported);setTab("audit");e.target.value=""}
function proposal(){const w=window.open("","_blank");if(!w)return;const rows=q.rows.slice(0,num(com.years)).map(r=>`<tr><td>${r.y}</td><td>${money0.format(r.b)}</td><td>${money0.format(r.o)}</td><td>${money0.format(r.p)}</td><td>${money0.format(r.n)}</td><td>${money0.format(r.cumulative)}</td></tr>`).join("");w.document.write(`<!doctype html><html><head><meta charset=utf-8><style>@page{size:A4;margin:14mm}body{font-family:Arial;color:#173040}.head{border-bottom:4px solid #c8ef55;padding:18px 0}.k{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:20px 0}.k div{border:1px solid #d9e3e5;border-radius:10px;padding:12px}.k b{display:block;font-size:20px}table{width:100%;border-collapse:collapse}th{background:#203f63;color:#fff}th,td{padding:7px;border-bottom:1px solid #e4eaec;text-align:right}th:first-child,td:first-child{text-align:left}</style></head><body><div class=head><h1>VIMALUX Intelligence</h1><b>${project.municipality}</b><br>${project.quotationId}</div><div class=k><div>CAPEX<b>${money0.format(q.capex)}</b></div><div>Annual OPEX<b>${money0.format(q.annualOpex)}</b></div><div>Annual net benefit<b>${money0.format(q.net)}</b></div><div>Monthly payment<b>${money2.format(q.monthly)}</b></div></div><h2>ROI</h2><p>Payback: ${q.payback.toFixed(1)} years · NPV: ${money0.format(q.npv)} · Lifecycle: ${money0.format(q.lifecycle)}</p><h2>Cash flow</h2><table><tr><th>Year</th><th>Benefit</th><th>OPEX</th><th>Payment</th><th>Net</th><th>Cumulative</th></tr>${rows}</table><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
const nav=[["projects","Projects"],["overview","Overview"],["audit","Audit & Lighting"],["solution","Solution"],["catalog","Product Catalogue"],["assumptions","Project Assumptions"],["finance","Finance & ROI"],["proposal","Proposal"]];
return <div style={s.shell}><aside style={s.side}><div style={s.brand}>VIMALUX<span>INTELLIGENCE</span></div><div style={s.badge}><small>ACTIVE PROJECT</small><b>{project.municipality}</b><span>{project.quotationId}</span></div>{nav.map(([id,l])=><button key={id} style={tab===id?s.on:s.nav} onClick={()=>setTab(id)}>{l}</button>)}<button style={s.import} onClick={()=>auditRef.current?.click()}>＋ Import audit</button><input hidden ref={auditRef} type="file" accept=".xlsx,.xls,.csv" onChange={importAudit}/></aside><main style={s.main}><header style={s.header}><div><small>QUOTATION WORKSPACE</small><h1>{tab==="projects"?"Projects":project.municipality}</h1></div><button style={s.primary} onClick={proposal}>Generate quotation</button></header>
{tab==="projects"&&<Card title="Projects"><button style={s.primary} onClick={()=>{const p=blankProject("New municipality");setProjects(x=>[...x,p]);setActiveId(p.id);setTab("overview")}}>＋ New project</button><div style={s.cards}>{projects.map(p=><button key={p.id} style={p.id===active.id?s.projectOn:s.project} onClick={()=>{setActiveId(p.id);setTab("overview")}}><b>{p.project.municipality}</b><span>{p.project.quotationId}</span></button>)}</div></Card>}
{tab==="overview"&&<><div style={s.grid}><Card title="Project"><TextField label="Municipality" value={project.municipality} onCommit={v=>patch({project:{...project,municipality:v}})}/><TextField label="Quotation ID" value={project.quotationId} onCommit={v=>patch({project:{...project,quotationId:v}})}/></Card><Card title="Summary"><Row l="Luminaires" v={q.qty}/><Row l="CAPEX" v={money0.format(q.capex)}/><Row l="Annual OPEX" v={money0.format(q.annualOpex)}/><Row l="Annual net benefit" v={money0.format(q.net)}/></Card></div><Kpis q={q} calc={calc}/></>}
{tab==="audit"&&<Card title="Audit & Lighting"><table style={s.table}><thead><tr><th>Group</th><th>Qty</th><th>Technology</th><th>Existing W</th><th>Selected luminaire</th><th>Smart</th><th>PowerAiD</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td><TextField value={g.label} onCommit={v=>setGroups(groups.map(x=>x.id===g.id?{...x,label:v}:x))}/></td><td><NumberField value={g.quantity} onCommit={v=>setGroups(groups.map(x=>x.id===g.id?{...x,quantity:v}:x))}/></td><td><select value={g.existingType} onChange={e=>setGroups(groups.map(x=>x.id===g.id?{...x,existingType:e.target.value}:x))}><option>SAP</option><option>LED</option><option>MH</option><option>Mercury</option><option>Unknown</option></select></td><td><NumberField value={g.existingWatt} onCommit={v=>setGroups(groups.map(x=>x.id===g.id?{...x,existingWatt:v}:x))}/></td><td><select value={g.productId} onChange={e=>setGroups(groups.map(x=>x.id===g.id?{...x,productId:e.target.value}:x))}>{activeProducts.map(p=><option key={p.id} value={p.id}>{p.name} · {p.watt}W</option>)}</select><button onClick={()=>{const r=recommendProduct(g.existingType,g.existingWatt,activeProducts);setGroups(groups.map(x=>x.id===g.id?{...x,productId:r.productId||x.productId}:x))}}>AI</button></td><td><input type="checkbox" checked={g.smart} onChange={e=>setGroups(groups.map(x=>x.id===g.id?{...x,smart:e.target.checked}:x))}/></td><td><input type="checkbox" checked={g.powerAid} onChange={e=>setGroups(groups.map(x=>x.id===g.id?{...x,powerAid:e.target.checked}:x))}/></td></tr>)}</tbody></table></Card>}
{tab==="solution"&&<div style={s.grid}><Card title="Solution selection"><Toggle label="Smart Lighting" value={com.smartEnabled} onChange={v=>setCom("smartEnabled",v)}/><Toggle label="CMS & connectivity" value={com.cmsEnabled} disabled={!com.smartEnabled} onChange={v=>setCom("cmsEnabled",v)}/><Toggle label="PowerAiD adaptive dimming" value={com.powerAidEnabled} disabled={!com.smartEnabled} onChange={v=>setCom("powerAidEnabled",v)}/></Card><Card title="Smart savings"><NumberField label="CLO saving %" value={ass.cloSavingPct} onCommit={v=>setAss("cloSavingPct",v)}/><NumberField label="PowerAiD additional saving % after CLO" value={ass.powerAidAdditionalSavingPct} onCommit={v=>setAss("powerAidAdditionalSavingPct",v)}/><NumberField label="PowerAiD fee share %" value={com.powerAidPerformanceSharePct} onCommit={v=>setCom("powerAidPerformanceSharePct",v)}/></Card></div>}
{tab==="catalog"&&<Card title="Product Catalogue"><button style={s.primary} onClick={()=>setProducts([...products,{id:`p-${Date.now()}`,name:"New luminaire",watt:40,lumen:6400,buyPrice:0,sellPrice:0,active:true}])}>＋ Add product</button><table style={s.table}><thead><tr><th>Name</th><th>W</th><th>Lumen</th><th>Cost</th><th>Sales</th><th>Active</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><TextField value={p.name} onCommit={v=>setProducts(products.map(x=>x.id===p.id?{...x,name:v}:x))}/></td><td><NumberField value={p.watt} onCommit={v=>setProducts(products.map(x=>x.id===p.id?{...x,watt:v}:x))}/></td><td><NumberField value={p.lumen} onCommit={v=>setProducts(products.map(x=>x.id===p.id?{...x,lumen:v}:x))}/></td><td><NumberField value={p.buyPrice} onCommit={v=>setProducts(products.map(x=>x.id===p.id?{...x,buyPrice:v}:x))}/></td><td><NumberField value={p.sellPrice} onCommit={v=>setProducts(products.map(x=>x.id===p.id?{...x,sellPrice:v}:x))}/></td><td><input type="checkbox" checked={p.active} onChange={e=>setProducts(products.map(x=>x.id===p.id?{...x,active:e.target.checked}:x))}/></td></tr>)}</tbody></table></Card>}
{tab==="assumptions"&&<div style={s.grid}><Card title="Energy assumptions"><NumberField label="Energy price €/kWh" value={ass.energyPrice} onCommit={v=>setAss("energyPrice",v)}/><NumberField label="Burning hours / year" value={ass.burningHours} onCommit={v=>setAss("burningHours",v)}/><NumberField label="Electricity increase % / year" value={ass.savingIndexationPct} onCommit={v=>setAss("savingIndexationPct",v)}/><NumberField label="CO₂ kg/kWh" value={ass.co2KgPerKwh} onCommit={v=>setAss("co2KgPerKwh",v)}/></Card><Card title="Commercial assumptions"><NumberField label="CMS €/lamp/year" value={com.cmsSellPerLampYear} onCommit={v=>setCom("cmsSellPerLampYear",v)}/><NumberField label="Smart node €/lamp" value={com.smartHardwareSellPerLamp} onCommit={v=>setCom("smartHardwareSellPerLamp",v)}/><NumberField label="Implementation €/lamp" value={com.implementationSellPerLamp} onCommit={v=>setCom("implementationSellPerLamp",v)}/><NumberField label="Maintenance after €/lamp/year" value={com.maintenanceAfterPerLamp} onCommit={v=>setCom("maintenanceAfterPerLamp",v)}/></Card></div>}
{tab==="finance"&&<><div style={s.grid}><Card title="Financing"><Select label="Model" value={com.model} options={["Cash purchase","Lighting as a Service","Noleggio Operativo","ESCO","PPP"]} onChange={v=>setCom("model",v)}/><NumberField label="Contract years" value={com.years} onCommit={v=>setCom("years",v)}/><NumberField label="Customer interest %" value={com.interestRate} onCommit={v=>setCom("interestRate",v)}/><NumberField label="Upfront payment" value={com.upfront} onCommit={v=>setCom("upfront",v)}/><NumberField label="Discount rate %" value={ass.discountRatePct} onCommit={v=>setAss("discountRatePct",v)}/></Card><Card title="Customer result"><Hero value={money2.format(q.monthly)} suffix="per month"/><Row l="Annual payment" v={money0.format(q.annualPayment)}/><Row l="Annual gross benefit" v={money0.format(q.gross)}/><Row l="Annual OPEX" v={money0.format(q.annualOpex)}/><Row l="Customer net / year" v={money0.format(q.net)}/><Row l="Simple payback" v={`${q.payback.toFixed(1)} years`}/><Row l="NPV" v={money0.format(q.npv)}/><Row l="Lifecycle savings" v={money0.format(q.lifecycle)}/></Card></div><Card title="20-year cash flow"><table style={s.table}><thead><tr><th>Year</th><th>Gross benefit</th><th>OPEX</th><th>Payment</th><th>Net cash flow</th><th>Cumulative</th></tr></thead><tbody>{q.rows.map(r=><tr key={r.y}><td>{r.y}</td><td>{money0.format(r.b)}</td><td>{money0.format(r.o)}</td><td>{money0.format(r.p)}</td><td>{money0.format(r.n)}</td><td>{money0.format(r.cumulative)}</td></tr>)}</tbody></table></Card></>}
{tab==="proposal"&&<Card title="Proposal"><Kpis q={q} calc={calc}/><button style={s.primary} onClick={proposal}>Generate customer proposal</button></Card>}
</main></div>}
function NumberField({label,value,onCommit}){const[d,setD]=useState(String(value??""));useEffect(()=>setD(String(value??"")),[value]);const commit=()=>{const n=num(d);setD(String(n));onCommit(n)};return<label style={s.field}>{label&&<span>{label}</span>}<input inputMode="decimal" value={d} onChange={e=>setD(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==="Enter"){e.currentTarget.blur()}}}/></label>}
function TextField({label,value,onCommit}){const[d,setD]=useState(String(value??""));useEffect(()=>setD(String(value??"")),[value]);return<label style={s.field}>{label&&<span>{label}</span>}<input value={d} onChange={e=>setD(e.target.value)} onBlur={()=>onCommit(d)}/></label>}
function Select({label,value,options,onChange}){return<label style={s.field}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Toggle({label,value,onChange,disabled}){return<label style={s.toggle}><span>{label}</span><input type="checkbox" checked={!!value} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}
function Card({title,children}){return<section style={s.card}><h2>{title}</h2>{children}</section>}
function Row({l,v}){return<div style={s.row}><span>{l}</span><b>{v}</b></div>}
function Hero({value,suffix}){return<div style={s.hero}>{value}<span>{suffix}</span></div>}
function Kpis({q,calc}){return<div style={s.kpis}><K l="CAPEX" v={money0.format(q.capex)}/><K l="Annual OPEX" v={money0.format(q.annualOpex)}/><K l="Annual net benefit" v={money0.format(q.net)}/><K l="Payback" v={`${q.payback.toFixed(1)} years`}/><K l="Energy reduction" v={`${(calc.totals.energyReductionPct||0).toFixed(1)}%`}/><K l="CO₂ reduction" v={`${(calc.finance.annualCo2Tonnes||0).toFixed(1)} t`}/></div>}
function K({l,v}){return<div style={s.kpi}><span>{l}</span><b>{v}</b></div>}
const s={shell:{minHeight:"100vh",display:"flex",fontFamily:"Inter,Segoe UI,Arial",background:"#f4f7f9",color:"#102f34"},side:{position:"fixed",inset:"0 auto 0 0",width:250,padding:20,background:"#0d2e32",color:"white",overflowY:"auto"},brand:{fontSize:22,fontWeight:900,marginBottom:20},badge:{display:"grid",gap:4,padding:14,background:"#173f44",borderRadius:12,marginBottom:12},nav:{width:"100%",padding:11,border:0,borderRadius:9,textAlign:"left",background:"transparent",color:"#c3d3d5",cursor:"pointer"},on:{width:"100%",padding:11,border:0,borderRadius:9,textAlign:"left",background:"#c8ef55",color:"#123236",fontWeight:800,cursor:"pointer"},import:{width:"100%",marginTop:15,padding:12},main:{marginLeft:250,padding:28,width:"calc(100% - 250px)"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:22},primary:{background:"#0d2e32",color:"white",border:0,borderRadius:9,padding:"12px 16px",fontWeight:800,cursor:"pointer"},card:{background:"white",padding:22,borderRadius:16,boxShadow:"0 5px 20px #0000000a",marginBottom:18},grid:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18},field:{display:"grid",gap:6,marginBottom:12},toggle:{display:"flex",justifyContent:"space-between",padding:"14px 0",borderBottom:"1px solid #e7eeee"},row:{display:"flex",justifyContent:"space-between",padding:"11px 0",borderBottom:"1px solid #e7eeee"},hero:{fontSize:38,fontWeight:900,margin:"15px 0"},kpis:{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:12,marginBottom:18},kpi:{background:"white",padding:16,borderRadius:14,border:"1px solid #dfe8ea",display:"grid",gap:8},table:{width:"100%",borderCollapse:"collapse"},cards:{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,marginTop:15},project:{padding:16,textAlign:"left",border:"1px solid #dce6e7",borderRadius:10,background:"#f7f9fa",display:"grid",gap:6},projectOn:{padding:16,textAlign:"left",border:"2px solid #a8ce31",borderRadius:10,background:"#eff8d8",display:"grid",gap:6}};