const translations = {
  it: {
    app: "VIMALUX Intelligence", projects: "Progetti", catalogue: "Catalogo Prodotti", priceAdmin: "Amministrazione Prezzi", internalReport: "Rapporto Interno", reset: "Reset dati locali",
    customer: "Cliente e Progetto", existing: "Illuminazione Esistente", solution: "Soluzione", pricing: "Prezzi di Progetto", assumptions: "Assunzioni", business: "Analisi Economica", report: "Rapporto",
    save: "Salvato automaticamente", add: "Aggiungi gruppo", remove: "Rimuovi", generate: "Genera PDF", italian: "Italiano", english: "English",
    preliminary: "Valutazione preliminare", capex: "CAPEX", annualOpex: "OPEX annuo", monthlyPayment: "Pagamento Mensile", annualNet: "Beneficio Netto Annuo", payback: "Tempo di Ritorno", npv: "VAN", lifecycle: "Risultato ciclo di vita", energyReduction: "Riduzione dei Consumi", co2Reduction: "Riduzione CO₂",
    baseline: "Consumo di riferimento", final: "Consumo finale", ledSaving: "Risparmio LED", cloSaving: "Risparmio CLO", powerSaving: "Risparmio PowerAiD", maintenanceSaving: "Risparmio manutenzione",
    technical: "Tecnica", savings: "Risparmi", financial: "Finanziaria", freight: "Trasporto", financingModel: "Tipo di progetto", financeSolution: "Finance solution", cashDeal: "Cash Deal", laas: "LaaS", ppp: "PPP",
    operatingHours: "Ore operative annue", energyPrice: "Prezzo energia (EUR/kWh)", sapFactor: "Fattore SAP", mhFactor: "Fattore MH", mercuryFactor: "Fattore Mercury", co2Factor: "CO₂ kg/kWh",
    cloPercent: "Percentuale CLO", powerAidPercent: "Percentuale PowerAiD", powerAidShare: "Quota PowerAiD", existingMaintenance: "Manutenzione esistente / lampada / anno", newMaintenance: "Nuova manutenzione / lampada / anno",
    contractYears: "Anni di contratto", interestRate: "Tasso di interesse (%)", upfrontPayment: "Anticipo", energyEscalation: "Aumento energia (%)", opexEscalation: "Aumento OPEX (%)", discountRate: "Tasso di attualizzazione (%)", analysisPeriod: "Periodo di analisi", freightCost: "Costo trasporto / lampada", freightSales: "Prezzo trasporto / lampada",
    yes: "Sì", no: "No", enabled: "Attivo", disabled: "Disattivo", units: "unità", years: "anni", notAvailable: "n/d",
    GO: "Il progetto appare economicamente sostenibile sulla base delle ipotesi dichiarate.", REVIEW: "Il progetto richiede un'ottimizzazione commerciale o tecnica.", NO_GO: "Il progetto non è economicamente sostenibile con le ipotesi attuali.",
  },
  en: {
    app: "VIMALUX Intelligence", projects: "Projects", catalogue: "Product Catalogue", priceAdmin: "Price Administration", internalReport: "Internal Report", reset: "Reset local data",
    customer: "Customer & Project", existing: "Existing Lighting", solution: "Solution", pricing: "Project Pricing", assumptions: "Assumptions", business: "Business Case", report: "Report",
    save: "Saved automatically", add: "Add group", remove: "Remove", generate: "Generate PDF", italian: "Italiano", english: "English",
    preliminary: "Preliminary assessment", capex: "CAPEX", annualOpex: "Annual OPEX", monthlyPayment: "Monthly Payment", annualNet: "Annual Net Benefit", payback: "Payback", npv: "NPV", lifecycle: "Lifecycle result", energyReduction: "Energy Reduction", co2Reduction: "CO₂ Reduction",
    baseline: "Baseline consumption", final: "Final consumption", ledSaving: "LED saving", cloSaving: "CLO saving", powerSaving: "PowerAiD saving", maintenanceSaving: "Maintenance saving",
    technical: "Technical", savings: "Savings", financial: "Financial", freight: "Freight", financingModel: "Project type", financeSolution: "Finance solution", cashDeal: "Cash Deal", laas: "LaaS", ppp: "PPP",
    operatingHours: "Annual operating hours", energyPrice: "Energy price (EUR/kWh)", sapFactor: "SAP factor", mhFactor: "MH factor", mercuryFactor: "Mercury factor", co2Factor: "CO₂ kg/kWh",
    cloPercent: "CLO percentage", powerAidPercent: "PowerAiD percentage", powerAidShare: "PowerAiD share percentage", existingMaintenance: "Existing maintenance / lamp / year", newMaintenance: "New maintenance / lamp / year",
    contractYears: "Contract years", interestRate: "Interest rate (%)", upfrontPayment: "Upfront payment", energyEscalation: "Energy escalation (%)", opexEscalation: "OPEX escalation (%)", discountRate: "Discount rate (%)", analysisPeriod: "Analysis period", freightCost: "Freight cost / lamp", freightSales: "Freight sales / lamp",
    yes: "Yes", no: "No", enabled: "Enabled", disabled: "Disabled", units: "units", years: "years", notAvailable: "n/a",
    GO: "The project appears economically sustainable based on the stated assumptions.", REVIEW: "The project requires commercial or technical optimisation.", NO_GO: "The project is not economically sustainable under the current assumptions.",
  },
};
export const useT = (language) => (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
translations.da = Object.fromEntries(Object.entries(translations.en).map(([key,value])=>[key,value]));
Object.assign(translations.it,{roi:"ROI annuo"});
Object.assign(translations.en,{roi:"Annual ROI"});
Object.assign(translations.da,{customer:"Kunde og projekt",existing:"Eksisterende belysning",solution:"Løsning",pricing:"Projektpriser",assumptions:"Forudsætninger",business:"Business case",report:"Kunderapport",projects:"Projekter",catalogue:"Produktkatalog",priceAdmin:"Prisadministration",internalReport:"Intern rapport",reset:"Nulstil lokale data",save:"Gemt automatisk",add:"Tilføj gruppe",remove:"Fjern",generate:"Generér PDF",preliminary:"Foreløbig vurdering",capex:"CAPEX",annualOpex:"Årlig OPEX",monthlyPayment:"Månedlig betaling",annualNet:"Årlig nettogevinst",payback:"Tilbagebetalingstid",roi:"Årligt ROI",npv:"NPV",lifecycle:"Livscyklusresultat",energyReduction:"Energireduktion",co2Reduction:"CO₂-reduktion",baseline:"Referenceforbrug",final:"Slutforbrug",ledSaving:"LED-besparelse",cloSaving:"CLO-besparelse",powerSaving:"PowerAiD-besparelse",maintenanceSaving:"Vedligeholdelsesbesparelse",technical:"Teknisk",savings:"Besparelser",financial:"Finansielt",freight:"Fragt",financingModel:"Projekttype",operatingHours:"Årlige driftstimer",energyPrice:"Energipris (EUR/kWh)",cloPercent:"CLO-procent",powerAidPercent:"PowerAiD-procent",powerAidShare:"PowerAiD-andel",contractYears:"Kontraktår",interestRate:"Rente (%)",upfrontPayment:"Udbetaling",energyEscalation:"Energiprisstigning (%)",opexEscalation:"OPEX-stigning (%)",discountRate:"Diskonteringsrente (%)",analysisPeriod:"Analyseperiode",yes:"Ja",no:"Nej",enabled:"Aktiveret",disabled:"Deaktiveret",years:"år",units:"enheder",notAvailable:"Ikke tilgængelig",GO:"Projektet vurderes økonomisk bæredygtigt ud fra de angivne forudsætninger.",REVIEW:"Projektet kræver kommerciel eller teknisk optimering.",NO_GO:"Projektet er ikke økonomisk bæredygtigt med de aktuelle forudsætninger."});
export const locale = (language) => language === "it" ? "it-IT" : language === "da" ? "da-DK" : "en-IE";
export const formatMoney = (value, language, currency = "EUR", digits = 0) => new Intl.NumberFormat(locale(language), { style: "currency", currency, useGrouping: "always", minimumFractionDigits: digits, maximumFractionDigits: digits }).format(Number(value) || 0);
export const formatNumber = (value, language, digits = 0) => new Intl.NumberFormat(locale(language), { useGrouping: "always", minimumFractionDigits: digits, maximumFractionDigits: digits }).format(Number(value) || 0);
export const formatPercent = (value, language) => `${formatNumber(value, language, 1)}%`;
