import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./additional-costs.css";
import "./solution-additional-costs.css";
import "./catalogueExtended.css";
import "./warranty.css";
import "./solutionAdditionalCosts.js";
import "./preliminaryProposalV2.js";
import "./reimportConfirmGuard.js";
import "./importedProductCategoryReconcile.js";
import "./catalogueTabsRuntime.js";
import "./defaultAssumptionsRuntime.js";
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
