import {jsPDF} from "jspdf";
import autoTable from "jspdf-autotable";

const num=v=>{const s=String(v??"").trim().replace(/\s/g,"");if(!s)return 0;if(s.includes(","))return Number(s.replace(/\./g,"").replace(",","."))||0;return Number(s)||0};
const pmt=(p,r,y)=>{const n=Math.max(1,Math.round(num(y)*12)),m=num(r)/1200;return m===0?p/n:p*m*Math.pow(1+m,n)/(Math.pow(1+m,n)-1)};
const nf0=new Intl.NumberFormat("it-IT",{maximumFractionDigits:0});
const nf1=new Intl.NumberFormat("it-IT",{minimumFractionDigits:1,maximumFractionDigits:1});
const nf2=new Intl.NumberFormat("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2});
const eur0=v=>`${nf0.format(num(v))} €`,eur2=v=>`${nf2.format(num(v))} €`;
const load=k=>{try{return JSON.parse(localStorage.getItem(k)||"null")}catch{return null}};

function getData(){
 const projects=load("vml-bc-projects")||[],activeId=localStorage.getItem("vml-bc-active"),p=projects.find(x=>x.id===activeId)||projects[0];
 const leds=load("vml-bc-led")||[],smart=load("vml-bc-smart")||[];if(!p)return null;
 const lm=new Map(leds.map(x=>[x.id,x])),sm=new Map(smart.map(x=>[x.id,x]));
 const ov=p.overrides||{},price=(x,k)=>num(ov[x?.id]?.[k]??x?.[k]);const a=p.assumptions||{},s=p.solution||{},f=p.finance||{};
 let qty=0,base=0,ledKwh=0,ledCapex=0,smartQty=0;
 for(const g of p.groups||[]){const q=num(g.quantity),w=num(g.existingWatt),fac=g.technology==="SAP"?num(a.sapFactor||1.2):g.technology==="MH"?num(a.mhFactor||1.15):g.technology==="Mercury"?num(a.mercuryFactor||1.15):1,l=lm.get(g.ledId);qty+=q;base+=q*w*fac*num(a.burningHours)/1000;ledKwh+=q*num(l?.watt)*num(a.burningHours)/1000;ledCapex+=q*num(g.ledOverride??price(l,"sales"));if(g.smart&&s.smartEnabled)smartQty+=q;}
 const clo=s.smartEnabled?ledKwh*num(a.cloPct)/100:0,after=Math.max(0,ledKwh-clo),pa=s.smartEnabled&&s.powerAidEnabled?after*num(a.powerAidPct)/100:0,final=Math.max(0,after-pa);
 const lcu=sm.get(s.lcuId),gw=sm.get(s.gatewayId),ant=sm.get(s.antennaId),meter=sm.get(s.meterId);
 const smartHardware=smartQty*price(lcu,"sales"),implementation=smartQty*price(lcu,"implementationSales"),gatewayCapex=num(s.gatewayQty)*price(gw,"sales"),antennaCapex=num(s.antennaQty)*price(ant,"sales"),meterCapex=num(s.meterQty)*price(meter,"sales"),freight=qty*num(a.freightSalesPerLamp),capex=ledCapex+smartHardware+implementation+gatewayCapex+antennaCapex+meterCapex+freight;
 const cms=s.cmsEnabled&&s.smartEnabled?smartQty*price(lcu,"annualSales"):0,gatewayOpex=s.cmsEnabled&&s.smartEnabled?num(s.gatewayQty)*price(gw,"annualSales"):0,powerAidFee=s.powerAidEnabled?pa*num(a.energyPrice)*num(a.powerAidSharePct)/100:0,annualOpex=cms+gatewayOpex+powerAidFee;
 const energySaving=(base-final)*num(a.energyPrice),maintenanceSaving=Math.max(0,qty*(num(a.maintenanceOld)-num(a.maintenanceNew))),gross=energySaving+maintenanceSaving,operatingNet=gross-annualOpex,monthly=f.model==="Cash Purchase"?0:pmt(Math.max(0,capex-num(f.upfront)),f.interestRate,f.years),annualPayment=monthly*12,customerNet=operatingNet-annualPayment;
 let npv=-capex,cumulative=-num(f.upfront);const rows=[];for(let y=1;y<=num(a.analysisYears||20);y++){const idx=Math.pow(1+num(a.energyEscalationPct)/100,y-1),benefit=gross*idx,opex=annualOpex*idx,payment=y<=num(f.years)?annualPayment:0,net=benefit-opex-payment;cumulative+=net;rows.push({year:y,benefit,opex,payment,net,cumulative});npv+=net/Math.pow(1+num(a.discountRatePct)/100,y)}
 const payback=operatingNet>0?capex/operatingNet:0,status=customerNet>0&&payback<=8?"GO":customerNet>0?"REVIEW":"NO-GO",energyReductionPct=base?100*(base-final)/base:0,co2=(base-final)*num(a.co2KgPerKwh)/1000;
 return{p,lm,sm,a,s,f,qty,base,final,ledCapex,smartHardware,implementation,gatewayCapex,antennaCapex,meterCapex,freight,capex,cms,gatewayOpex,powerAidFee,annualOpex,energySaving,maintenanceSaving,monthly,annualPayment,customerNet,npv,lifecycle:rows.at(-1)?.cumulative||0,payback,status,energyReductionPct,co2,rows};
}

function makePdf(){const x=getData();if(!x)return;const it=(x.p.project?.language||"it")==="it";const T=it?{
 title:"Business Case Preliminare",summary:"Sintesi esecutiva",assessment:"Valutazione preliminare",sustainable:"Il progetto risulta economicamente sostenibile sulla base delle ipotesi indicate.",decision:"Decisione",capex:"CAPEX",monthly:"Pagamento mensile",net:"Beneficio netto annuo",payback:"Payback",energy:"Riduzione energia",co2:"Riduzione CO₂",customer:"Cliente e progetto",client:"Cliente",province:"Provincia / Regione",contact:"Referente",project:"Progetto",sales:"Consulente VIMALUX",date:"Data",ass:"Ipotesi di calcolo",points:"Numero punti luce",tech:"Tecnologia esistente",avgw:"Potenza media esistente",led:"LED proposto",ledw:"Potenza LED",hours:"Ore di funzionamento",price:"Costo energia",years:"Durata contratto",model:"Modello finanziario",smart:"Smart Lighting",power:"PowerAiD",yes:"SÌ",no:"NO",benefits:"Benefici energetici ed economici",baseline:"Consumo iniziale",final:"Consumo finale",es:"Risparmio energia",ms:"Risparmio manutenzione",opex:"OPEX annuo",npv:"VAN",life:"Beneficio cumulato",breakdown:"Dettaglio CAPEX e OPEX",component:"Componente CAPEX",amount:"Importo",ocomp:"Componente OPEX annuo",cash:"Cash flow cliente",year:"Anno",benefit:"Beneficio",payment:"Pagamento",cumulative:"Cumulato",next:"Prossimo passo",nextText:"Validazione preliminare completata. Il passo successivo comprende censimento GPS, classificazione UNI 11248, progettazione illuminotecnica, assegnazione prodotti e offerta tecnica definitiva tramite VIMALUX Planner.",disc:"Questa analisi rappresenta una valutazione preliminare basata su quantità aggregate e potenze medie. Le quantità definitive, il progetto illuminotecnico, le verifiche UNI 11248, la classificazione stradale, il censimento GPS e l'assegnazione dei prodotti saranno sviluppati nel VIMALUX Planner.",yearsWord:"anni"}:{
 title:"Preliminary Business Case",summary:"Executive summary",assessment:"Preliminary assessment",sustainable:"The project appears economically viable based on the stated assumptions.",decision:"Decision",capex:"CAPEX",monthly:"Monthly payment",net:"Annual net benefit",payback:"Payback",energy:"Energy reduction",co2:"CO₂ reduction",customer:"Customer and project",client:"Customer",province:"Province / Region",contact:"Contact",project:"Project",sales:"VIMALUX consultant",date:"Date",ass:"Calculation assumptions",points:"Number of luminaires",tech:"Existing technology",avgw:"Average existing wattage",led:"Proposed LED",ledw:"LED wattage",hours:"Operating hours",price:"Energy price",years:"Contract duration",model:"Financial model",smart:"Smart Lighting",power:"PowerAiD",yes:"YES",no:"NO",benefits:"Energy and financial benefits",baseline:"Baseline consumption",final:"Final consumption",es:"Energy saving",ms:"Maintenance saving",opex:"Annual OPEX",npv:"NPV",life:"Cumulative benefit",breakdown:"CAPEX and OPEX breakdown",component:"CAPEX component",amount:"Amount",ocomp:"Annual OPEX component",cash:"Customer cash flow",year:"Year",benefit:"Benefit",payment:"Payment",cumulative:"Cumulative",next:"Next step",nextText:"Preliminary validation completed. The next step includes GPS census, UNI 11248 classification, photometric design, product assignment and final technical proposal through VIMALUX Planner.",disc:"This analysis is a preliminary assessment based on aggregated quantities and average wattages. Final quantities, photometric design, UNI 11248 checks, road classification, GPS census and product assignment will be developed in VIMALUX Planner.",yearsWord:"years"};
 const d=new jsPDF({unit:"mm",format:"a4"}),dark=[16,56,64],green=[200,239,85],muted=[90,108,113],p=x.p,c=p.customer||{},pr=p.project||{},groups=p.groups||[],first=groups[0]||{},led=x.lm.get(first.ledId),avgW=x.qty?groups.reduce((s,g)=>s+num(g.quantity)*num(g.existingWatt),0)/x.qty:0;
 const header=()=>{d.setFillColor(...dark);d.rect(0,0,210,24,"F");d.setTextColor(255);d.setFont("helvetica","bold");d.setFontSize(18);d.text("VIMALUX Intelligence",14,15);d.setFontSize(9);d.text(T.title,143,9);d.text(pr.businessCaseId||"",143,14);d.text(c.name||"",143,19);d.setFillColor(...green);d.rect(0,24,210,2,"F")};
 const title=(t,y)=>{d.setTextColor(...dark);d.setFont("helvetica","bold");d.setFontSize(15);d.text(t,14,y)};header();title(T.summary,36);
 autoTable(d,{startY:41,theme:"grid",styles:{fontSize:7.2,cellPadding:2.7},headStyles:{fillColor:dark},head:[[T.decision,T.capex,T.monthly,T.net,T.payback,T.energy,T.co2]],body:[[x.status,eur0(x.capex),eur2(x.monthly),eur0(x.customerNet),`${nf1.format(x.payback)} ${T.yearsWord}`,`${nf1.format(x.energyReductionPct)}%`,`${nf1.format(x.co2)} t/anno`]]});
 let y=d.lastAutoTable.finalY+5;d.setFillColor(239,249,216);d.roundedRect(14,y,182,14,2,2,"F");d.setTextColor(...dark);d.setFont("helvetica","bold");d.setFontSize(9);d.text(`${T.assessment}: ${x.status}`,18,y+5);d.setFont("helvetica","normal");d.setFontSize(8);d.text(T.sustainable,18,y+10,{maxWidth:174});y+=20;title(T.customer,y);
 const customerRows=[[T.client,c.name||"-"],[T.province,[c.province,c.region].filter(Boolean).join(" / ")||"-"],[T.contact,[c.contact,c.title,c.email,c.phone].filter(Boolean).join(" · ")||"-"],[T.project,pr.name||"-"],[T.sales,pr.salesPerson||"-"],[T.date,pr.date||"-"]];autoTable(d,{startY:y+4,theme:"plain",styles:{fontSize:8,cellPadding:1.3},columnStyles:{0:{fontStyle:"bold",textColor:muted},1:{cellWidth:120}},body:customerRows});
 y=d.lastAutoTable.finalY+4;title(T.ass,y);const assRows=[[T.points,nf0.format(x.qty)],[T.tech,groups.map(g=>g.technology).filter((v,i,a)=>a.indexOf(v)===i).join(", ")],[T.avgw,`${nf1.format(avgW)} W`],[T.led,led?.name||"-"],[T.ledw,`${led?.watt||0} W`],[T.hours,`${nf0.format(x.a.burningHours)} h/anno`],[T.price,`${nf2.format(x.a.energyPrice)} €/kWh`],[T.years,`${nf0.format(x.f.years)} ${T.yearsWord}`],[T.model,x.f.model],[T.smart,x.s.smartEnabled?T.yes:T.no],[T.power,x.s.powerAidEnabled?T.yes:T.no]];autoTable(d,{startY:y+4,theme:"grid",styles:{fontSize:7.4,cellPadding:1.8},headStyles:{fillColor:dark},body:assRows,columnStyles:{0:{fontStyle:"bold",cellWidth:52}}});
 d.addPage();header();title(T.benefits,36);autoTable(d,{startY:41,theme:"grid",styles:{fontSize:8,cellPadding:2.4},body:[[T.baseline,`${nf0.format(x.base)} kWh/anno`],[T.final,`${nf0.format(x.final)} kWh/anno`],[T.es,eur0(x.energySaving)],[T.ms,eur0(x.maintenanceSaving)],[T.opex,eur0(x.annualOpex)],[T.monthly,eur2(x.monthly)],[T.npv,eur0(x.npv)],[T.life,eur0(x.lifecycle)]]});y=d.lastAutoTable.finalY+6;title(T.breakdown,y);autoTable(d,{startY:y+4,theme:"grid",styles:{fontSize:7.4,cellPadding:2},headStyles:{fillColor:dark},head:[[T.component,T.amount,T.ocomp,T.amount]],body:[["LED",eur0(x.ledCapex),"CMS",eur0(x.cms)],[T.smart,eur0(x.smartHardware),"Gateway OPEX",eur0(x.gatewayOpex)],["Implementazione",eur0(x.implementation),"PowerAiD",eur0(x.powerAidFee)],["Gateway",eur0(x.gatewayCapex),T.opex,eur0(x.annualOpex)],["Antenne",eur0(x.antennaCapex),"",""],["Misuratori",eur0(x.meterCapex),"",""],["Trasporto",eur0(x.freight),"",""],["Totale CAPEX",eur0(x.capex),"",""]]});
 d.addPage();header();title(T.cash,36);autoTable(d,{startY:41,theme:"striped",styles:{fontSize:7.2,cellPadding:2},headStyles:{fillColor:dark},head:[[T.year,T.benefit,"OPEX",T.payment,"Netto",T.cumulative]],body:x.rows.slice(0,num(x.f.years)).map(r=>[r.year,eur0(r.benefit),eur0(r.opex),eur0(r.payment),eur0(r.net),eur0(r.cumulative)]),rowPageBreak:"avoid",showHead:"everyPage"});y=d.lastAutoTable.finalY+7;title(T.next,y);d.setFont("helvetica","normal");d.setFontSize(8.5);d.setTextColor(...dark);d.text(T.nextText,14,y+6,{maxWidth:182});d.setFontSize(7.5);d.setTextColor(...muted);d.text(T.disc,14,280,{maxWidth:182});const pages=d.getNumberOfPages();for(let i=1;i<=pages;i++){d.setPage(i);d.setFontSize(7);d.setTextColor(...muted);d.text(`${i}/${pages}`,196,290,{align:"right"})}d.save(`${pr.businessCaseId||"Business_Case"}_${(c.name||"Customer").replace(/\s+/g,"_")}.pdf`)}

function install(){document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;const t=(b.textContent||"").toLowerCase();if(t.includes("generate")&&t.includes("pdf")){e.preventDefault();e.stopImmediatePropagation();makePdf()}},true)}
install();
