const IT={
"PRELIMINARY BUSINESS CASE":"STUDIO PRELIMINARE DI FATTIBILITÀ",
"Projects":"Progetti","Customer & Project":"Cliente e Progetto","Existing Lighting":"Illuminazione esistente","Solution":"Soluzione","Project Pricing":"Prezzi di progetto","Assumptions":"Assunzioni","Business Case":"Business Case","Report":"Rapporto","Admin":"Amministrazione",
"Preliminary Business Case Report":"Studio preliminare di fattibilità economica","Customer-ready PDF generated from the current customer, product, pricing, solution and financial data.":"PDF pronto per il cliente generato dai dati correnti relativi a cliente, prodotti, prezzi, soluzione e finanza.",
"Decision":"Valutazione","Annual net benefit":"Beneficio netto annuo","Payback":"Tempo di ritorno","Generate business case PDF":"Genera PDF business case","Review report":"Verifica rapporto",
"Solution selection":"Selezione della soluzione","Additional equipment":"Apparecchiature aggiuntive","Smart Lighting":"Illuminazione intelligente","CMS & connectivity":"CMS e connettività","PowerAiD adaptive dimming":"Regolazione adattiva PowerAiD","LCU controller":"Controller LCU","Gateway quantity":"Quantità gateway","Antenna quantity":"Quantità antenne","Energy meter":"Misuratore di energia","Meter quantity":"Quantità misuratori",
"Customer":"Cliente","Province":"Provincia","Region":"Regione","Country":"Paese","Contact person":"Referente","Title":"Ruolo","Email":"E-mail","Telephone":"Telefono","Project name":"Nome progetto","Business Case No.":"N. Business Case","Sales person":"Responsabile VIMALUX","Date":"Data","Language":"Lingua","Currency":"Valuta"
};
const EN=Object.fromEntries(Object.entries(IT).map(([k,v])=>[v,k]));
function getState(){try{const ps=JSON.parse(localStorage.getItem('vml-bc-projects')||'[]');const id=localStorage.getItem('vml-bc-active');return ps.find(p=>p.id===id)||ps[0]||null}catch{return null}}
function saveLanguage(lang){try{const ps=JSON.parse(localStorage.getItem('vml-bc-projects')||'[]');const id=localStorage.getItem('vml-bc-active');const out=ps.map(p=>p.id===(id||ps[0]?.id)?{...p,project:{...p.project,language:lang}}:p);localStorage.setItem('vml-bc-projects',JSON.stringify(out));location.reload()}catch{}}
function translate(lang){const dict=lang==='it'?IT:EN;document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0){const t=(el.textContent||'').trim();if(dict[t])el.textContent=dict[t]}})}
function addLanguage(){if(document.getElementById('vml-lang-switch'))return;const p=getState();const wrap=document.createElement('div');wrap.id='vml-lang-switch';wrap.style.cssText='position:fixed;top:14px;right:18px;z-index:9999;background:#fff;border:1px solid #d5dfe2;border-radius:10px;padding:8px 10px;box-shadow:0 6px 18px rgba(0,0,0,.08);font:600 13px Arial';wrap.innerHTML='<label style="margin-right:8px">Lingua / Language</label><select id="vml-lang-select" style="padding:6px 8px;border:1px solid #cbd5d8;border-radius:6px"><option value="it">Italiano</option><option value="en">English</option></select>';document.body.appendChild(wrap);const s=wrap.querySelector('select');s.value=p?.project?.language||'it';s.onchange=e=>saveLanguage(e.target.value)}
function addLcuSummary(){const p=getState();if(!p||!p.solution?.smartEnabled)return;const headings=[...document.querySelectorAll('h1,h2,h3')];const target=headings.find(x=>(x.textContent||'').includes('Solution selection')||(x.textContent||'').includes('Selezione della soluzione'));if(!target||document.getElementById('vml-lcu-summary'))return;const qty=(p.groups||[]).filter(g=>g.smart!==false).reduce((s,g)=>s+(Number(g.quantity)||0),0);const box=document.createElement('div');box.id='vml-lcu-summary';box.style.cssText='margin-top:18px;padding:16px 18px;border:1px solid #dbe5e8;border-radius:10px;background:#f7fafb;font:600 15px Arial;color:#103840';box.innerHTML=`<div style="font-size:13px;color:#667b82;margin-bottom:4px">${p.project?.language==='en'?'Calculated LCU quantity':'Quantità LCU calcolata'}</div><div style="font-size:26px">${new Intl.NumberFormat('it-IT').format(qty)} LCU</div><div style="font-size:12px;font-weight:400;color:#667b82;margin-top:4px">${p.project?.language==='en'?'1 LCU for each luminaire assigned to Smart Lighting':'1 LCU per ogni apparecchio assegnato allo Smart Lighting'}</div>`;target.parentElement.appendChild(box)}
function run(){const p=getState();addLanguage();translate(p?.project?.language||'it');addLcuSummary()}
const mo=new MutationObserver(()=>run());mo.observe(document.documentElement,{childList:true,subtree:true});setTimeout(run,300);setInterval(run,1500);
